#!/usr/bin/with-contenv bash
cd ${HOME}
exec /opt/conda/bin/jupyter lab \
    --notebook-dir="${HOME}" \
    --ip=0.0.0.0 \
    --allow-root \
    --port=8888 \
    --ServerApp.token="" \
    --ServerApp.password="" \
    --ServerApp.allow_origin="*" \
    --ServerApp.base_url=${NB_PREFIX} \
    --ServerApp.authenticate_prometheus=False
