[tool.poetry]
name = "content-scoring-train"
version = "0.1.0"
description = "Docker image for registering model for document content-scoring"
authors = ["Amaury de Guillebon <amaury.deguillebon@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.8.16"
lightgbm = "^3.2.1"
pyarrow = "^7.0.0"
joblib = "^1.1.0"
tracking = {path = "../../../libs/tracking"}

[tool.poetry.group.dev.dependencies]
pytest = "7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
