---
version: 2
updates:
  # ====================================
  # GITHUB ACTIONS
  # ====================================

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/London"
      day: "monday"

  # ====================================
  # DOCKER
  # ====================================

  # kubeflow torch cpu

  - package-ecosystem: pip
    directory: /docker/kubeflow-torch-cpu
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "12:00"
      timezone: "Europe/London"
      day: "monday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # neuron-inference

  - package-ecosystem: pip
    directory: /docker/neuron-inference
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "14:00"
      timezone: "Europe/London"
      day: "monday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # kubeflow torch gpu

  - package-ecosystem: pip
    directory: /docker/kubeflow-torch-gpu
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "16:00"
      timezone: "Europe/London"
      day: "monday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # kubeflow torch inf

  - package-ecosystem: pip
    directory: /docker/kubeflow-torch-inf
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "17:00"
      timezone: "Europe/London"
      day: "monday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # gpu base

  - package-ecosystem: pip
    directory: /docker/gpu-base
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "18:00"
      timezone: "Europe/London"
      day: "monday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # dask base

  - package-ecosystem: pip
    directory: /docker/dask-base
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "20:00"
      timezone: "Europe/London"
      day: "monday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # ====================================
  # LIBS
  # ====================================

  # core lib

  - package-ecosystem: pip
    directory: /libs/core
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "21:00"
      timezone: "Europe/London"
      day: "monday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # compile lib

  - package-ecosystem: pip
    directory: /libs/compile
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "22:00"
      timezone: "Europe/London"
      day: "monday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # models lib

  - package-ecosystem: pip
    directory: /libs/models
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "23:00"
      timezone: "Europe/London"
      day: "monday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # nlp lib

  - package-ecosystem: pip
    directory: /libs/nlp
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "00:00"
      timezone: "Europe/London"
      day: "tuesday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # serving lib

  - package-ecosystem: pip
    directory: /libs/serving
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "01:00"
      timezone: "Europe/London"
      day: "tuesday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # hashing lib

  - package-ecosystem: pip
    directory: /libs/hashing
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "02:00"
      timezone: "Europe/London"
      day: "tuesday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # tracking lib

  - package-ecosystem: pip
    directory: /libs/tracking
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "Europe/London"
      day: "tuesday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # ====================================
  # PROJECTS
  # ====================================

  # KEYWORDS

  ## compile

  - package-ecosystem: pip
    directory: /projects/keywords/compile
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "04:00"
      timezone: "Europe/London"
      day: "tuesday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  ## serve
  - package-ecosystem: pip
    directory: /projects/keywords/serve
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "05:00"
      timezone: "Europe/London"
      day: "tuesday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  ## train
  - package-ecosystem: pip
    directory: /projects/keywords/train
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "06:00"
      timezone: "Europe/London"
      day: "tuesday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]


  # SUMMARIZATION

  ## serve
  - package-ecosystem: pip
    directory: /projects/summarization/serve
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "07:00"
      timezone: "Europe/London"
      day: "tuesday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]


  # GCH-SUMMARIZATION

  ## train
  - package-ecosystem: pip
    directory: /projects/gch-summarization/train
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/London"
      day: "tuesday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # ENTITY-LINKING

  ## serve
  - package-ecosystem: pip
    directory: /projects/entity-linking/serve
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/London"
      day: "tuesday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # NER

  ## compile

  - package-ecosystem: pip
    directory: /projects/ner/compile
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "10:00"
      timezone: "Europe/London"
      day: "tuesday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  ## serve
  - package-ecosystem: pip
    directory: /projects/ner/serve
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "11:00"
      timezone: "Europe/London"
      day: "tuesday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  ## train
  - package-ecosystem: pip
    directory: /projects/ner/train
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "12:00"
      timezone: "Europe/London"
      day: "tuesday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # Sentiment

  ## compile

  - package-ecosystem: pip
    directory: /projects/sentiment/compile
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "13:00"
      timezone: "Europe/London"
      day: "tuesday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  ## serve
  - package-ecosystem: pip
    directory: /projects/sentiment/serve
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "14:00"
      timezone: "Europe/London"
      day: "tuesday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  ## train
  - package-ecosystem: pip
    directory: /projects/sentiment/train
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "15:00"
      timezone: "Europe/London"
      day: "tuesday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # IPTC

  ## ingest
  - package-ecosystem: pip
    directory: /projects/iptc/ingest
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "16:00"
      timezone: "Europe/London"
      day: "tuesday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # ====================================
  # APPS
  # ====================================

  # PROMPT

  ## backend
  - package-ecosystem: pip
    directory: /apps/prompt/backend
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "18:00"
      timezone: "Europe/London"
      day: "tuesday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]


  ## frontend
  - package-ecosystem: npm
    directory: /apps/prompt/frontend
    target-branch: develop
    open-pull-requests-limit: 1
    schedule:
      interval: "monthly"
      time: "19:00"
      timezone: "Europe/London"
      day: "tuesday"
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]
