version: 2
updates:
  # ====================================
  # GITHUB ACTIONS
  # ====================================

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # ====================================
  # DOCKER
  # ====================================

  # fastapi-serve

  - package-ecosystem: "pip"
    directory: "/docker/fastapi-serve"
    schedule:
      interval: "monthly"

  # kubeflow base

  - package-ecosystem: "pip"
    directory: "/docker/kubeflow-base"
    schedule:
      interval: "monthly"

  # kubeflow data science

  - package-ecosystem: "pip"
    directory: "/docker/kubeflow-data-science"
    schedule:
      interval: "monthly"

  # kubeflow jax cpu

  - package-ecosystem: "pip"
    directory: "/docker/kubeflow-jax-cpu"
    schedule:
      interval: "monthly"

  # kubeflow jupyter

  - package-ecosystem: "pip"
    directory: "/docker/kubeflow-jupyter"
    schedule:
      interval: "monthly"

  # kubeflow numpy

  - package-ecosystem: "pip"
    directory: "/docker/kubeflow-numpy"
    schedule:
      interval: "monthly"

  # kubeflow torch cpu

  - package-ecosystem: "pip"
    directory: "/docker/kubeflow-torch-cpu"
    schedule:
      interval: "monthly"

  # python base

  - package-ecosystem: "pip"
    directory: "/docker/python-base"
    schedule:
      interval: "monthly"

  # ====================================
  # LIBS
  # ====================================

  # core lib

  - package-ecosystem: "pip"
    directory: "/libs/core"
    schedule:
      interval: "monthly"

  # ====================================
  # PROJECTS
  # ====================================

  # KEYBERT

  ## serve

  - package-ecosystem: "pip"
    directory: "/projects/keybert/serve"
    schedule:
      interval: "monthly"
