---
version: 2
updates:
  # ====================================
  # GITHUB ACTIONS
  # ====================================

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: monthly
      time: 09:00
      timezone: Europe/London

  # ====================================
  # DOCKER
  # ====================================

  # fastapi-serve

  - package-ecosystem: pip
    directory: /docker/fastapi-serve
    target-branch: develop
    schedule:
      interval: monthly
      time: 09:00
      timezone: Europe/London

    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # kubeflow base

  - package-ecosystem: pip
    directory: /docker/kubeflow-base
    target-branch: develop
    schedule:
      interval: monthly
      time: 09:00
      timezone: Europe/London
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # kubeflow data science

  - package-ecosystem: pip
    directory: /docker/kubeflow-data-science
    target-branch: develop
    schedule:
      interval: monthly
      time: 09:00
      timezone: Europe/London
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # kubeflow jax cpu

  - package-ecosystem: pip
    directory: /docker/kubeflow-jax-cpu
    target-branch: develop
    schedule:
      interval: monthly
      time: 09:00
      timezone: Europe/London
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # kubeflow jupyter

  - package-ecosystem: pip
    directory: /docker/kubeflow-jupyter
    target-branch: develop
    schedule:
      interval: monthly
      time: 09:00
      timezone: Europe/London
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # kubeflow numpy

  - package-ecosystem: pip
    directory: /docker/kubeflow-numpy
    target-branch: develop
    schedule:
      interval: monthly
      time: 09:00
      timezone: Europe/London
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # kubeflow torch cpu

  - package-ecosystem: pip
    directory: /docker/kubeflow-torch-cpu
    target-branch: develop
    schedule:
      interval: monthly
      time: 09:00
      timezone: Europe/London
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # python base

  - package-ecosystem: pip
    directory: /docker/python-base
    target-branch: develop
    schedule:
      interval: monthly
      time: 09:00
      timezone: Europe/London
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # neuron-compile

  - package-ecosystem: pip
    directory: /docker/neuron-compile
    target-branch: develop
    schedule:
      interval: monthly
      time: 09:00
      timezone: Europe/London
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # neuron-inference

  - package-ecosystem: pip
    directory: /docker/neuron-inference
    target-branch: develop
    schedule:
      interval: monthly
      time: 09:00
      timezone: Europe/London
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # ====================================
  # LIBS
  # ====================================

  # core lib

  - package-ecosystem: pip
    directory: /libs/core
    target-branch: develop
    schedule:
      interval: monthly
      time: 09:00
      timezone: Europe/London
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # compile lib

  - package-ecosystem: pip
    directory: /libs/ml_compile
    target-branch: develop
    schedule:
      interval: monthly
      time: 09:00
      timezone: Europe/London
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # ====================================
  # PROJECTS
  # ====================================

  # KEYWORDS

  ## serve
  - package-ecosystem: pip
    directory: /projects/keywords/serve
    target-branch: develop
    schedule:
      interval: monthly
      time: 09:00
      timezone: Europe/London
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  ## train
  - package-ecosystem: pip
    directory: /projects/keywords/train
    target-branch: develop
    schedule:
      interval: monthly
      time: 09:00
      timezone: Europe/London
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]

  # SUMMARIZATION

  ## serve
  - package-ecosystem: pip
    directory: /projects/summarization/serve
    target-branch: develop
    schedule:
      interval: monthly
      time: 09:00
      timezone: Europe/London
    ignore:
      - dependency-name: '*'
        update-types: [version-update:semver-patch]
