version: 2
updates:
  # ====================================
  # GITHUB ACTIONS
  # ====================================

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/London"

  # ====================================
  # DOCKER
  # ====================================

  # fastapi-serve

  - package-ecosystem: "pip"
    directory: "/docker/fastapi-serve"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/London"

    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # kubeflow base

  - package-ecosystem: "pip"
    directory: "/docker/kubeflow-base"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/London"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # kubeflow data science

  - package-ecosystem: "pip"
    directory: "/docker/kubeflow-data-science"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/London"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # kubeflow jax cpu

  - package-ecosystem: "pip"
    directory: "/docker/kubeflow-jax-cpu"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/London"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # kubeflow jupyter

  - package-ecosystem: "pip"
    directory: "/docker/kubeflow-jupyter"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/London"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # kubeflow numpy

  - package-ecosystem: "pip"
    directory: "/docker/kubeflow-numpy"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/London"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # kubeflow torch cpu

  - package-ecosystem: "pip"
    directory: "/docker/kubeflow-torch-cpu"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/London"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # python base

  - package-ecosystem: "pip"
    directory: "/docker/python-base"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/London"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # ====================================
  # LIBS
  # ====================================

  # core lib

  - package-ecosystem: "pip"
    directory: "/libs/core"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/London"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # ====================================
  # PROJECTS
  # ====================================

  # KEYWORDS

  ## serve

  # python
  - package-ecosystem: "pip"
    directory: "/projects/keywords/serve"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/London"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # docker
  - package-ecosystem: "docker"
    directory: "/projects/keywords/serve"
    schedule:
      interval: "monthly"
      time: "09:00"
      timezone: "Europe/London"
    registries:
      - ecr-prod

# REGISTRIES

registries:
  ecr-prod:
    type: docker-registry
    url: https://211212199399.dkr.ecr.us-east-1.amazonaws.com
    username: ${{ secrets.AWS_ACCESS_KEY_ID }}
    password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
