categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "dependencies"
      - "patch"
change-template: "- $TITLE - PR: #$NUMBER (@$AUTHOR)"
template: |
  ## What’s Changed
  $CHANGES
filter-by-commitish: true
