---

services:

  # =============================================
  # TRAIN
  # =============================================

  train:
    build:
      context: ../../
      dockerfile: projects/visitor-estimation/train/Dockerfile
      target: ${TARGET_BUILD_STAGE:-development}
      network: host
      args:
        AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID:-690763002009}
        PROJECT: visitor-estimation
        COMPONENT: train
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG}
    volumes:
      - type: bind
        source: train
        target: /projects/visitor-estimation/train
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-2.amazonaws.com/visitor-estimation-train:${IMAGE_TAG:-latest}
    command: [python, -m, src.train_model]
    profiles: [train]
    environment:
      NEPTUNE_API_TOKEN: ${NEPTUNE_API_TOKEN}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      ONCLUSIVEML_FEATURE_STORE_PROJECT: ${ONCLUSIVEML_FEATURE_STORE_PROJECT}
      ONCLUSIVEML_FEATURE_STORE_MYSQL_HOST: ${ONCLUSIVEML_FEATURE_STORE_MYSQL_HOST}
      ONCLUSIVEML_FEATURE_STORE_MYSQL_USER: ${ONCLUSIVEML_FEATURE_STORE_MYSQL_USER}
      ONCLUSIVEML_FEATURE_STORE_MYSQL_PORT: ${ONCLUSIVEML_FEATURE_STORE_MYSQL_PORT}
      ONCLUSIVEML_FEATURE_STORE_MYSQL_PASSWORD: ${ONCLUSIVEML_FEATURE_STORE_MYSQL_PASSWORD}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_CLUSTER_ID: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_CLUSTER_ID}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_CLUSTER_REGION: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_CLUSTER_REGION}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_DATABASE: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_DATABASE}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_USER: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_USER}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_S3_STAGING_DIRECTORY: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_S3_STAGING_DIRECTORY}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_IAM_ROLE: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_IAM_ROLE}
      ONCLUSIVEML_FEATURE_STORE_DATASET_UPLOAD_BUCKET: ${ONCLUSIVEML_FEATURE_STORE_DATASET_UPLOAD_BUCKET}
      ONCLUSIVEML_FEATURE_STORE_DATASET_UPLOAD_DIR: ${ONCLUSIVEML_FEATURE_STORE_DATASET_UPLOAD_DIR}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_TIMESTAMP_FIELD: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_TIMESTAMP_FIELD}
      ONCLUSIVEML_FEATURE_STORE_N_RECORDS_SAMPLE: ${ONCLUSIVEML_FEATURE_STORE_N_RECORDS_SAMPLE}
      ONCLUSIVEML_FEATURE_STORE_N_RECORDS_FULL: ${ONCLUSIVEML_FEATURE_STORE_N_RECORDS_FULL}
    env_file: train/config/prod.env
    hostname: onclusive-ml
    networks: [onclusive-net]

  train-unit:
    volumes:
      - type: bind
        source: train
        target: /projects/visitor-estimation/train
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-2.amazonaws.com/visitor-estimation-train:${IMAGE_TAG:-latest}
    command: [python, -m, pytest, tests/unit, -ra, -vv, --capture=no]
    profiles: [unit]
    environment:
      NEPTUNE_API_TOKEN: ${NEPTUNE_API_TOKEN}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      ONCLUSIVEML_FEATURE_STORE_PROJECT: ${ONCLUSIVEML_FEATURE_STORE_PROJECT}
      ONCLUSIVEML_FEATURE_STORE_MYSQL_HOST: ${ONCLUSIVEML_FEATURE_STORE_MYSQL_HOST}
      ONCLUSIVEML_FEATURE_STORE_MYSQL_USER: ${ONCLUSIVEML_FEATURE_STORE_MYSQL_USER}
      ONCLUSIVEML_FEATURE_STORE_MYSQL_PORT: ${ONCLUSIVEML_FEATURE_STORE_MYSQL_PORT}
      ONCLUSIVEML_FEATURE_STORE_MYSQL_PASSWORD: ${ONCLUSIVEML_FEATURE_STORE_MYSQL_PASSWORD}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_CLUSTER_ID: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_CLUSTER_ID}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_CLUSTER_REGION: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_CLUSTER_REGION}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_DATABASE: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_DATABASE}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_USER: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_USER}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_S3_STAGING_DIRECTORY: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_S3_STAGING_DIRECTORY}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_IAM_ROLE: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_IAM_ROLE}
      ONCLUSIVEML_FEATURE_STORE_DATASET_UPLOAD_BUCKET: ${ONCLUSIVEML_FEATURE_STORE_DATASET_UPLOAD_BUCKET}
      ONCLUSIVEML_FEATURE_STORE_DATASET_UPLOAD_DIR: ${ONCLUSIVEML_FEATURE_STORE_DATASET_UPLOAD_DIR}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_TIMESTAMP_FIELD: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_TIMESTAMP_FIELD}
      ONCLUSIVEML_FEATURE_STORE_N_RECORDS_SAMPLE: ${ONCLUSIVEML_FEATURE_STORE_N_RECORDS_SAMPLE}
      ONCLUSIVEML_FEATURE_STORE_N_RECORDS_FULL: ${ONCLUSIVEML_FEATURE_STORE_N_RECORDS_FULL}
    env_file: train/config/prod.env
    hostname: onclusive-ml
    networks: [onclusive-net]

  # =============================================
  # SERVE
  # =============================================

  # serving image
  serve:
    volumes:
      - serve-volume:/projects/visitor-estimation/serve/models
    build:
      context: ../../
      dockerfile: projects/visitor-estimation/serve/Dockerfile
      target: ${TARGET_BUILD_STAGE:-development}
      cache_to:
        - type=s3,bucket=ecr-cache-sub-${DEPLOYMENT},region=us-east-2,name=visitor-estimation-serve,mode=max
      cache_from:
        - type=s3,bucket=ecr-cache-sub-${DEPLOYMENT},region=us-east-2,name=visitor-estimation-serve
      args:
        AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID:-690763002009}
        PROJECT: visitor-estimation
        COMPONENT: serve
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG}
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-2.amazonaws.com/visitor-estimation-serve:${IMAGE_TAG}
    command: [python, -m, src.serve.__main__]
    env_file: serve/config/${DEPLOYMENT:-prod}.env
    profiles: [serve, functional, load]
    ports:
      - 8000:8000
    hostname: onclusiveml
    networks:
      - onclusive-net
    healthcheck:
      test: [CMD, curl, -f, http://serve:8000/visitor-estimation/v1/ready]
      interval: 1m30s
      retries: 3
      start_period: 1m
      timeout: 1m10s

  # utility service: downloading the compiled model artifact that will be served
  serve-download-model:
    volumes:
      - serve-volume:/projects/visitor-estimation/serve/models
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-2.amazonaws.com/visitor-estimation-serve:${IMAGE_TAG}
    command: [python, -m, src.download]
    profiles: [serve, integration, functional, load]
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      ONCLUSIVEML_NEPTUNE_API_TOKEN: ${NEPTUNE_API_TOKEN}
      NEPTUNE_CLIENT_MODE: read-only
    env_file: serve/config/${DEPLOYMENT:-prod}.env
    hostname: onclusiveml
    networks: [onclusive-net]

  # unit tests
  # - do NOT include model artifact
  # - do NOT include REST model server process
  serve-unit:
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-2.amazonaws.com/visitor-estimation-serve:${IMAGE_TAG}
    env_file: serve/config/${DEPLOYMENT:-prod}.env
    command: [python, -m, pytest, tests/unit, -ra, -vv, --capture=no]
    profiles: [unit]
    hostname: onclusiveml
    networks:
      - onclusive-net

  # functional tests
  # - include model artifact
  # - include REST model server process
  serve-functional:
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-2.amazonaws.com/visitor-estimation-serve:${IMAGE_TAG}
    command: [python, -m, pytest, tests/functional, -ra, -vv, --capture=no]
    env_file: serve/config/${DEPLOYMENT:-prod}.env
    profiles: [functional]
    hostname: onclusiveml
    networks:
      - onclusive-net
    depends_on:
      serve:
        condition: service_healthy


networks:
  onclusive-net:
volumes :
  serve-volume:
