---

services:

  # =============================================
  # TRAIN
  # =============================================

  train:
    build:
      context: ../../
      dockerfile: projects/visitor-estimation/train/Dockerfile
      target: ${TARGET_BUILD_STAGE:-development}
      network: host
      args:
        AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID:-690763002009}
        PROJECT: visitor-estimation
        COMPONENT: train
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG}
    volumes:
      - type: bind
        source: train
        target: /projects/visitor-estimation/train
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-2.amazonaws.com/visitor-estimation-train:${IMAGE_TAG:-latest}
    command: [python, -m, src.train_model]
    profiles: [train]
    environment:
      NEPTUNE_API_TOKEN: ${NEPTUNE_API_TOKEN}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      ONCLUSIVEML_FEATURE_STORE_PROJECT: ${ONCLUSIVEML_FEATURE_STORE_PROJECT}
      ONCLUSIVEML_FEATURE_STORE_MYSQL_HOST: ${ONCLUSIVEML_FEATURE_STORE_MYSQL_HOST}
      ONCLUSIVEML_FEATURE_STORE_MYSQL_USER: ${ONCLUSIVEML_FEATURE_STORE_MYSQL_USER}
      ONCLUSIVEML_FEATURE_STORE_MYSQL_PORT: ${ONCLUSIVEML_FEATURE_STORE_MYSQL_PORT}
      ONCLUSIVEML_FEATURE_STORE_MYSQL_PASSWORD: ${ONCLUSIVEML_FEATURE_STORE_MYSQL_PASSWORD}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_CLUSTER_ID: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_CLUSTER_ID}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_CLUSTER_REGION: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_CLUSTER_REGION}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_DATABASE: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_DATABASE}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_USER: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_USER}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_S3_STAGING_DIRECTORY: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_S3_STAGING_DIRECTORY}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_IAM_ROLE: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_IAM_ROLE}
      ONCLUSIVEML_FEATURE_STORE_DATASET_UPLOAD_BUCKET: ${ONCLUSIVEML_FEATURE_STORE_DATASET_UPLOAD_BUCKET}
      ONCLUSIVEML_FEATURE_STORE_DATASET_UPLOAD_DIR: ${ONCLUSIVEML_FEATURE_STORE_DATASET_UPLOAD_DIR}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_TIMESTAMP_FIELD: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_TIMESTAMP_FIELD}
      ONCLUSIVEML_FEATURE_STORE_N_RECORDS_SAMPLE: ${ONCLUSIVEML_FEATURE_STORE_N_RECORDS_SAMPLE}
      ONCLUSIVEML_FEATURE_STORE_N_RECORDS_FULL: ${ONCLUSIVEML_FEATURE_STORE_N_RECORDS_FULL}
    env_file: train/config/prod.env
    hostname: onclusive-ml
    networks: [onclusive-net]

  train-unit:
    volumes:
      - type: bind
        source: train
        target: /projects/visitor-estimation/train
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-2.amazonaws.com/visitor-estimation-train:${IMAGE_TAG:-latest}
    command: [python, -m, pytest, tests/unit, -ra, -vv, --capture=no]
    profiles: [unit]
    environment:
      NEPTUNE_API_TOKEN: ${NEPTUNE_API_TOKEN}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      ONCLUSIVEML_FEATURE_STORE_PROJECT: ${ONCLUSIVEML_FEATURE_STORE_PROJECT}
      ONCLUSIVEML_FEATURE_STORE_MYSQL_HOST: ${ONCLUSIVEML_FEATURE_STORE_MYSQL_HOST}
      ONCLUSIVEML_FEATURE_STORE_MYSQL_USER: ${ONCLUSIVEML_FEATURE_STORE_MYSQL_USER}
      ONCLUSIVEML_FEATURE_STORE_MYSQL_PORT: ${ONCLUSIVEML_FEATURE_STORE_MYSQL_PORT}
      ONCLUSIVEML_FEATURE_STORE_MYSQL_PASSWORD: ${ONCLUSIVEML_FEATURE_STORE_MYSQL_PASSWORD}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_CLUSTER_ID: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_CLUSTER_ID}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_CLUSTER_REGION: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_CLUSTER_REGION}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_DATABASE: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_DATABASE}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_USER: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_USER}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_S3_STAGING_DIRECTORY: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_S3_STAGING_DIRECTORY}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_IAM_ROLE: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_IAM_ROLE}
      ONCLUSIVEML_FEATURE_STORE_DATASET_UPLOAD_BUCKET: ${ONCLUSIVEML_FEATURE_STORE_DATASET_UPLOAD_BUCKET}
      ONCLUSIVEML_FEATURE_STORE_DATASET_UPLOAD_DIR: ${ONCLUSIVEML_FEATURE_STORE_DATASET_UPLOAD_DIR}
      ONCLUSIVEML_FEATURE_STORE_REDSHIFT_TIMESTAMP_FIELD: ${ONCLUSIVEML_FEATURE_STORE_REDSHIFT_TIMESTAMP_FIELD}
      ONCLUSIVEML_FEATURE_STORE_N_RECORDS_SAMPLE: ${ONCLUSIVEML_FEATURE_STORE_N_RECORDS_SAMPLE}
      ONCLUSIVEML_FEATURE_STORE_N_RECORDS_FULL: ${ONCLUSIVEML_FEATURE_STORE_N_RECORDS_FULL}
    env_file: train/config/prod.env
    hostname: onclusive-ml
    networks: [onclusive-net]

networks:
  onclusive-net:
