---
ci:
  skip: [hadolint-docker]
default_language_version:
    # force all unspecified python hooks to run python3
    python: python3.8
repos:
  # =================================
  # PYTHON
  # =================================

  # python formatter
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        files: ^(libs|docker|projects|apps)/.*\.py$

  # Lint: Python
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        files: ^(libs|docker|apps|projects|tests)/.*\.py$

  # static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        files: ^(libs|projects)/.*\.py$
        exclude: ^(libs/.*/tests/|projects/.*/tests|docker/.*/tests)
        args: ["--explicit-package-bases"]

  # isort
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^(libs|docker|apps|projects|tests)/.*\.py$

  # # Autoformat: YAML, JSON, Markdown, etc.
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v2.4.1
  #   hooks:
  #     - id: prettier
  #       exclude: "^apps/entity-fishing/backend/"

  # Lint: Dockerfile
  - repo: https://github.com/hadolint/hadolint.git
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        entry: hadolint/hadolint:v2.12.0 hadolint
        exclude: "^apps/entity-fishing/backend/"

  # Lint: Bash scripts
  - repo: https://github.com/openstack-dev/bashate.git
    rev: 2.1.0
    hooks:
      - id: bashate
        args: ["--ignore=E006"]
        exclude: "^apps/entity-fishing/backend/"

  # # Lint: Shell scripts
  # - repo: https://github.com/shellcheck-py/shellcheck-py
  #   rev: v0.8.0.1
  #   hooks:
  #     - id: shellcheck
  #       args: ["-x"]
  #       exclude: "^apps/entity-fishing/backend/"

  # # Lint: Markdown
  # - repo: https://github.com/igorshubovych/markdownlint-cli
  #   rev: v0.29.0
  #   hooks:
  #     - id: markdownlint
  #       args: ["--fix"]
  #       exclude: "^apps/entity-fishing/backend/"
