---
ci                      :
  skip: [hadolint-docker]
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3.8

repos                   :
  # =================================
  # GENERIC
  # =================================

  # generic hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^apps/entity-fishing/backend/
      - id: trailing-whitespace
        exclude: ^apps/entity-fishing/backend/
      - id: check-merge-conflict
      - id: detect-private-key

 # Checks yaml syntax
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0    # or other specific tag
    hooks:
      - id: yamllint
        args: [--strict, -c=.yamllint.yaml]
        exclude: ^(.pre-commit-config.yaml|apps/entity-fishing/backend/data|.github/dependabot.yaml)

# Autoformat: YAML,docker...
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.1    # or other specific tag
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2', --colons]
        exclude: ^(.pre-commit-config.yaml|apps/entity-fishing/backend/data|.github/dependabot.yaml)


  # =================================
  # PYTHON
  # =================================

  # python formatter
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        files: ^(libs|docker|projects|apps)/.*\.py$

  # Lint: Python
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        files: ^(libs|docker|apps|projects|tests)/.*\.py$

  # static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        files: ^(libs|projects)/.*\.py$
        exclude:
          ^(libs/.*/tests/|projects/.*/tests|docker/.*/tests|projects/entity-linking/serve/src/predict/entity_fishing.py|projects/summarization/serve/src/_init.py|projects/summarization/serve/src/routes/health.py|projects/summarization/serve/src/predict/summarization.py|projects/keywords/compile/src/test_compiled_model/conftest.py)
        args:
          - --explicit-package-bases
          - --no-warn-unused-ignores

  # isort
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^(libs|docker|apps|projects|tests)/.*\.py$

  # =================================
  # DOCKER
  # =================================

  # Lint: Dockerfile
  - repo: https://github.com/hadolint/hadolint.git
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        entry: hadolint/hadolint:v2.12.0 hadolint
        exclude: ^apps/entity-fishing/backend/

  # Lint: Bash scripts
  - repo: https://github.com/openstack-dev/bashate.git
    rev: 2.1.0
    hooks:
      - id: bashate
        args: [--ignore=E006]
        exclude: ^apps/entity-fishing/backend/

  # Lint: Shell scripts
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.1
    hooks:
      - id: shellcheck
        args: [-x]
        exclude: ^apps/entity-fishing/backend/
