---
ci                      :
  skip: [hadolint-docker]
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3.8

repos                   :
  # =================================
  # GENERIC
  # =================================

  # generic hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^apps/entity-fishing/backend/
      - id: trailing-whitespace
        exclude: ^apps/entity-fishing/backend/
      - id: check-merge-conflict
      - id: detect-private-key

 # Checks yaml syntax
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0    # or other specific tag
    hooks:
      - id: yamllint
        args: [--strict, -c=.yamllint.yaml]
        exclude: ^(.pre-commit-config.yaml|.github/dependabot.yaml|apps/entity-fishing/backend/data)

# Autoformat: YAML,docker...
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.1    # or other specific tag
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2', --colons]
        exclude: ^(.pre-commit-config.yaml|.github/dependabot.yaml|apps/entity-fishing/backend/data)


  # =================================
  # PYTHON
  # =================================

  # python formatter
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        files: ^(libs|docker|projects|apps)/.*\.py$

  # Lint: Python
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        files: ^(libs|docker|apps|projects|tests)/.*\.py$
        exclude: ^(libs/serving/onclusiveml/serving/rest/serve/server_utils\.py)

  # static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        files: ^(libs|projects)/.*\.py$
        exclude:
          ^(libs/.*/tests/|projects/.*/tests|projects/.*/test_compiled_model|projects/.*/settings.py|projects/topic-summarization/serve/src/serve/model.py|projects/topic-summarization/backfill/src/__init__.py|projects/entity-linking/backfill/src/backfill/__init__.py|projects/entity-linking/backfill/src/backfill/__main__.py|projects/entity-linking/backfill/src/backfill/pipeline.py|projects/gch-summarization/train/src/train_model.py|projects/gch-summarization/train/src/__init__.py|projects/gch-summarization/serve/src/serve/__init__.py|projects/gch-summarization/serve/src/__init__.py|projects/gch-summarization/serve/src/download.py|projects/gch-summarization/serve/src/serve/__main__.py|projects/gch-summarization/serve/src/serve/artifacts.py|projects/gch-summarization/serve/src/serve/model.py|projects/gch-summarization/serve/src/serve/schemas.py|projects/gch-summarization/serve/src/serve/server.py|projects/content-scoring/train/src/train_model.py|projects/iptc-multi/serve/src/serve/__main__.py|projects/iptc-multi/serve/src/serve/schemas.py|projects/summarization/serve/src/serve/__main__.py|libs/models/onclusiveml/models/bela/|libs/models/onclusiveml/models/multiel/|projects/entity-linking/train/src/train_model.py|projects/transcript-segmentation/serve/src/serve/exceptions.py)
        args:
          - --explicit-package-bases
          - --no-warn-unused-ignores
        additional_dependencies: [types-requests]

  # isort
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^(libs|docker|apps|projects|tests)/.*\.py$

  # docstring
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        args:
          - --convention=google
          - --count
          - --add-ignore=D105,D106,D107,D203
        additional_dependencies: [toml, tomli]
        exclude: ^(bin/)

  # =================================
  # DOCKER
  # =================================

  # Lint: Dockerfile
  - repo: https://github.com/hadolint/hadolint.git
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        entry: hadolint/hadolint:v2.12.0 hadolint
        exclude: ^apps/entity-fishing/backend/

  # Lint: Bash scripts
  - repo: https://github.com/openstack-dev/bashate.git
    rev: 2.1.0
    hooks:
      - id: bashate
        args: [--ignore=E006]
        exclude: ^apps/entity-fishing/backend/

  # Lint: Shell scripts
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.1
    hooks:
      - id: shellcheck
        args: [-x]
        exclude: ^apps/entity-fishing/backend/
