[tool.poetry]
name = "keywords-compile"
version = "0.1.0"
description = "Implementation of Keywords ML model compilation, including validation."
authors = ["Sebastian Scherer <sebastian.scherer@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.8.16"
keybert = "0.7.0"
regex = "2022.10.31"

[tool.poetry.group.dev.dependencies]
pydantic = "1.10.4"
pytest = "7.2.0"
pytest-mock = "3.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
