[tool.poetry]
name = "keywords-compile"
version = "0.1.0"
description = "Implementation of Keywords ML model compilation, including validation."
authors = ["Sebastian Scherer <sebastian.scherer@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.9.19"
core = {path = "../../../libs/core"}
tracking = {path = "../../../libs/tracking"}
models = {path = "../../../libs/models", extras = ["keywords"]}

[tool.poetry.group.dev.dependencies]
pytest = "7.2.0"
pytest-mock = "3.10.0"

[tool.poetry.group.debug.dependencies]
debugpy = "1.8.1"

[[tool.poetry.source]]
name = "aws-neuron"
url = "https://pip.repos.neuron.amazonaws.com/"
priority = "supplemental"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
