[tool.poetry]
name = "keywords-compile"
version = "0.1.0"
description = "Implementation of Keywords ML model compilation, including validation."
authors = ["Sebastian Scherer <sebastian.scherer@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.8.16"
tracking = {path = "../../../libs/tracking"}
models = {path = "../../../libs/models"}
pydantic = {version = "1.10.4", extras = ["dotenv"]}

[tool.poetry.group.dev.dependencies]

pytest = "7.2.0"
pytest-mock = "3.10.0"


[[tool.poetry.source]]
name = "aws-neuron"
url = "https://pip.repos.neuron.amazonaws.com/"
default = false
secondary = true


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
