[tool.poetry]
name = "gpt_summarization-serve"
version = "0.1.0"
description = "Implementation of GPT3 API."
authors = ["Syed Reza <syed.reza@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.8.16"
regex = "2022.10.31"
openai = "0.27.2"

core = {path = "../../../libs/core"}

[tool.poetry.group.dev.dependencies]
pydantic = "1.10.4"
uvicorn = "0.20.0"
starlette = "0.25.0"
fastapi = {version = "0.92.0", extras = ["all"]}
pytest = "7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
