[tool.poetry]
name = "neuron-inference"
version = "0.1.0"
description = "Context to score (i.e. run inference on) a torch based graph that has been compiled to torch neuron."
authors = ["Sebastian Scherer sebastian.scherer@onclusive.com>"]
readme = "README.md"
packages = [{include = "neuron_inference"}]

[tool.poetry.dependencies]
python = "3.10.14"
torch = "1.12.1"
torch-neuron = {version = "1.12.1.2.9.74.0", source = "aws-neuron"}
transformers = "^4.39.2"

[[tool.poetry.source]]
name = "aws-neuron"
url = "https://pip.repos.neuron.amazonaws.com"
priority = "supplemental"

[tool.poetry.group.compilation.dependencies]
pytest = "8.2.0"
neuron-cc = {version = "1.14.3.0", source = "aws-neuron"}
transformers = "^4.39.2"

[tool.poetry.group.dev.dependencies]
pytest = "8.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
