---

services:
  # =============================================
  # SERVE
  # =============================================

  # serving image
  serve:
    build:
      context: ../../
      dockerfile: projects/iptc-multi/serve/Dockerfile
      target: ${TARGET_BUILD_STAGE:-development}
      cache_to:
        - type=s3,bucket=ecr-cache-sub-${DEPLOYMENT},region=us-east-2,name=iptc-multi-serve,mode=max
      cache_from:
        - type=s3,bucket=ecr-cache-sub-${DEPLOYMENT},region=us-east-2,name=iptc-multi-serve
      args:
        AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID:-690763002009}
        PROJECT: iptc-multi
        COMPONENT: serve
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG}
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-2.amazonaws.com/iptc-multi-serve:${IMAGE_TAG}
    command: [python, -m, src.serve.__main__]
    profiles: [serve, functional]
    ports:
      - 8000:8000
    environment:
      ONCLUSIVEML_SERVING_LOGCONFIG_SERVICE: iptc-multi-serve
      ONCLUSIVEML_SERVING_LOGCONFIG_LEVEL: 20
      ONCLUSIVEML_SERVING_LOGCONFIG_JSON_FORMAT: yes
      ENVIRONMENT: dev
      DOCS_URL: /iptc-multi/docs
      ONCLUSIVEML_SERVING_UVICORN_APP: src.serve.__main__:model_server
      ONCLUSIVEML_SERVING_UVICORN_WORKERS: 1
      ONCLUSIVEML_SERVING_UVICORN_PORT: 8000
      ONCLUSIVEML_SERVING_API_VERSION: v1
      PROMETHEUS_MULTIPROC_DIR: /tmp
    env_file: serve/config/${DEPLOYMENT:-prod}.env
    hostname: onclusiveml
    networks:
      - onclusive-net
    depends_on:
      serve-iptc-00000000:
        condition: service_healthy
      serve-iptc-04000000:
        condition: service_healthy
      serve-iptc-20000170:
        condition: service_healthy
      serve-iptc-20000763:
        condition: service_healthy
    healthcheck:
      test: [CMD, curl, -f, http://serve:8000/iptc-multi/v1/ready]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  # unit tests
  serve-unit:
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-2.amazonaws.com/iptc-multi-serve:${IMAGE_TAG}
    command: [python, -m, pytest, tests/unit, -ra, -vv, --capture=no]
    profiles: [unit]
    environment:
      ENVIRONMENT: dev
      DOCS_URL: /iptc-multi/docs
    hostname: onclusiveml
    networks:
      - onclusive-net

  # integration tests
  serve-integration:
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-2.amazonaws.com/iptc-multi-serve:${IMAGE_TAG}
    command: [python, -m, pytest, tests/integration, -ra, -vv, --capture=no]
    profiles: [integration]
    environment:
      ONCLUSIVEML_SERVING_UVICORN_PORT: 8000
      ONCLUSIVEML_SERVING_API_VERSION: v1
    hostname: onclusiveml
    networks:
      - onclusive-net

  # functional tests
  # - include REST model server process
  serve-functional:
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-2.amazonaws.com/iptc-multi-serve:${IMAGE_TAG}
    command: [python, -m, pytest, tests/functional, -ra, -vv, --capture=no]
    environment:
      ONCLUSIVEML_SERVING_UVICORN_PORT: 8000
      ONCLUSIVEML_SERVING_API_VERSION: v1
    profiles: [functional]
    hostname: onclusiveml
    networks:
      - onclusive-net
    depends_on:
      serve:
        condition: service_healthy


  serve-iptc-00000000:
    devices:
      - /dev/neuron0:/dev/neuron0
    volumes:
      - serve-volume:/projects/iptc/serve/models
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-2.amazonaws.com/iptc-serve:${IMAGE_TAG}
    environment:
      ONCLUSIVEML_SERVING_LOGCONFIG_SERVICE: iptc-serve
      ONCLUSIVEML_SERVING_LOGCONFIG_LEVEL: 10
      ONCLUSIVEML_SERVING_LOGCONFIG_JSON_FORMAT: false
      ONCLUSIVEML_SERVING_MODEL_DIRECTORY: models/IP00000000-COMPILED-113
      ONCLUSIVEML_NEPTUNE_PROJECT: onclusive/iptc-00000000
      ONCLUSIVEML_NEPTUNE_MODEL: 00000000-COMPILED
      ONCLUSIVEML_SERVING_MODEL_NAME: iptc-00000000
      ONCLUSIVEML_NEPTUNE_WITH_ID: IP00000000-COMPILED-113
      ONCLUSIVEML_TRACKING_BACKEND_USE_S3_BACKEND: yes
      ONCLUSIVEML_TRACKING_BACKEND_ENVIRONMENT: prod
      ONCLUSIVEML_SERVING_UVICORN_APP: src.serve.__main__:model_server
      ONCLUSIVEML_SERVING_UVICORN_RELOAD: true
      ONCLUSIVEML_SERVING_UVICORN_RELOAD_DIRS: src/serve/
      ONCLUSIVEML_SERVING_UVICORN_WORKERS: 1
      NEURON_RT_NUM_CORES: 1
      ONCLUSIVEML_SERVING_UVICORN_PORT: 8000
      ONCLUSIVEML_SERVING_API_VERSION: v1
      ONCLUSIVEML_TRACKING_LOGGER_LEVEL: 10 # 10=DEBUG
      NEPTUNE_PROJECT: onclusive/iptc-00000000
      NEPTUNE_MODEL_ID: IPTC-COMPILED
      NEPTUNE_MODEL_VERSION_ID: IP00000000-COMPILED-113
      IPTC_MODEL_NAME: iptc-00000000
      COMPILED_PROJECT: onclusive/iptc-00000000
      COMPILED_MODEL: IP00000000-COMPILED
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      ONCLUSIVEML_NEPTUNE_API_TOKEN: ${NEPTUNE_API_TOKEN}
    profiles: [serve, functional]
    command:
      - /bin/sh
      - -c
      - |
        python -m src.download
        python -m src.serve.__main__
    ports:
      - 8001:8000
    hostname: onclusiveml
    networks:
      - onclusive-net
    healthcheck:
      test: [CMD, curl, -f, http://serve-iptc-00000000:8000/iptc-00000000/v1/ready]
      interval: 15s
      retries: 5
      start_period: 10s
      timeout: 30s

  serve-iptc-04000000:
    devices:
      - /dev/neuron1:/dev/neuron1
    volumes:
      - serve-volume:/projects/iptc/serve/models
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-2.amazonaws.com/iptc-serve:${IMAGE_TAG}
    environment:
      ONCLUSIVEML_SERVING_LOGCONFIG_SERVICE: iptc-serve
      ONCLUSIVEML_SERVING_LOGCONFIG_LEVEL: 10
      ONCLUSIVEML_SERVING_LOGCONFIG_JSON_FORMAT: false
      ONCLUSIVEML_SERVING_MODEL_DIRECTORY: models/IP04000000-COMPILED-58
      ONCLUSIVEML_NEPTUNE_PROJECT: onclusive/iptc-04000000
      ONCLUSIVEML_NEPTUNE_MODEL: IP04000000-COMPILED
      ONCLUSIVEML_SERVING_MODEL_NAME: iptc-04000000
      ONCLUSIVEML_NEPTUNE_WITH_ID: IP04000000-COMPILED-58
      ONCLUSIVEML_TRACKING_BACKEND_USE_S3_BACKEND: yes
      ONCLUSIVEML_TRACKING_BACKEND_ENVIRONMENT: prod
      ONCLUSIVEML_SERVING_UVICORN_APP: src.serve.__main__:model_server
      ONCLUSIVEML_SERVING_UVICORN_RELOAD: true
      ONCLUSIVEML_SERVING_UVICORN_RELOAD_DIRS: src/serve/
      ONCLUSIVEML_SERVING_UVICORN_WORKERS: 1
      NEURON_RT_NUM_CORES: 1
      ONCLUSIVEML_SERVING_UVICORN_PORT: 8000
      ONCLUSIVEML_SERVING_API_VERSION: v1
      ONCLUSIVEML_TRACKING_LOGGER_LEVEL: 10 # 10=DEBUG
      NEPTUNE_PROJECT: onclusive/iptc-04000000
      NEPTUNE_MODEL_ID: IPTC-COMPILED
      NEPTUNE_MODEL_VERSION_ID: IP04000000-COMPILED-58
      IPTC_MODEL_NAME: iptc-04000000
      COMPILED_PROJECT: onclusive/iptc-04000000
      COMPILED_MODEL: IP04000000-COMPILED
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      ONCLUSIVEML_NEPTUNE_API_TOKEN: ${NEPTUNE_API_TOKEN}
    profiles: [serve, functional]
    command:
      - /bin/sh
      - -c
      - |
        python -m src.download
        python -m src.serve.__main__
    ports:
      - 8002:8000
    hostname: onclusiveml
    networks:
      - onclusive-net
    healthcheck:
      test: [CMD, curl, -f, http://serve-iptc-04000000:8000/iptc-04000000/v1/ready]
      interval: 15s
      retries: 5
      start_period: 10s
      timeout: 30s

  serve-iptc-20000170:
    devices:
      - /dev/neuron2:/dev/neuron2
    volumes:
      - serve-volume:/projects/iptc/serve/models
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-2.amazonaws.com/iptc-serve:${IMAGE_TAG}
    environment:
      ONCLUSIVEML_SERVING_LOGCONFIG_SERVICE: iptc-serve
      ONCLUSIVEML_SERVING_LOGCONFIG_LEVEL: 10
      ONCLUSIVEML_SERVING_LOGCONFIG_JSON_FORMAT: false
      ONCLUSIVEML_SERVING_MODEL_DIRECTORY: models/IP20000170-COMPILED-9
      ONCLUSIVEML_NEPTUNE_PROJECT: onclusive/iptc-20000170
      ONCLUSIVEML_NEPTUNE_MODEL: IP20000170-COMPILED
      ONCLUSIVEML_SERVING_MODEL_NAME: iptc-20000170
      ONCLUSIVEML_NEPTUNE_WITH_ID: IP20000170-COMPILED-9
      ONCLUSIVEML_TRACKING_BACKEND_USE_S3_BACKEND: yes
      ONCLUSIVEML_TRACKING_BACKEND_ENVIRONMENT: prod
      ONCLUSIVEML_SERVING_UVICORN_APP: src.serve.__main__:model_server
      ONCLUSIVEML_SERVING_UVICORN_RELOAD: true
      ONCLUSIVEML_SERVING_UVICORN_RELOAD_DIRS: src/serve/
      ONCLUSIVEML_SERVING_UVICORN_WORKERS: 1
      NEURON_RT_NUM_CORES: 1
      ONCLUSIVEML_SERVING_UVICORN_PORT: 8000
      ONCLUSIVEML_SERVING_API_VERSION: v1
      ONCLUSIVEML_TRACKING_LOGGER_LEVEL: 10 # 10=DEBUG
      NEPTUNE_PROJECT: onclusive/iptc-20000170
      NEPTUNE_MODEL_ID: IP20000170-COMPILED
      NEPTUNE_MODEL_VERSION_ID: IP20000170-COMPILED-9
      IPTC_MODEL_NAME: iptc-20000170
      COMPILED_PROJECT: onclusive/iptc-20000170
      COMPILED_MODEL: IP20000170-COMPILED
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      ONCLUSIVEML_NEPTUNE_API_TOKEN: ${NEPTUNE_API_TOKEN}
    profiles: [serve, functional]
    command:
      - /bin/sh
      - -c
      - |
        python -m src.download
        python -m src.serve.__main__
    ports:
      - 8003:8000
    hostname: onclusiveml
    networks:
      - onclusive-net
    healthcheck:
      test: [CMD, curl, -f, http://serve-iptc-20000170:8000/iptc-20000170/v1/ready]
      interval: 15s
      retries: 5
      start_period: 10s
      timeout: 30s

  serve-iptc-20000763:
    devices:
      - /dev/neuron3:/dev/neuron3
    volumes:
      - serve-volume:/projects/iptc/serve/models
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-2.amazonaws.com/iptc-serve:${IMAGE_TAG}
    environment:
      ONCLUSIVEML_SERVING_LOGCONFIG_SERVICE: iptc-serve
      ONCLUSIVEML_SERVING_LOGCONFIG_LEVEL: 10
      ONCLUSIVEML_SERVING_LOGCONFIG_JSON_FORMAT: false
      ONCLUSIVEML_SERVING_MODEL_DIRECTORY: models/IP20000763-COMPILED-2
      ONCLUSIVEML_NEPTUNE_PROJECT: onclusive/iptc-20000763
      ONCLUSIVEML_NEPTUNE_MODEL: 20000763-COMPILED
      ONCLUSIVEML_SERVING_MODEL_NAME: iptc-20000763
      ONCLUSIVEML_NEPTUNE_WITH_ID: IP20000763-COMPILED-2
      ONCLUSIVEML_TRACKING_BACKEND_USE_S3_BACKEND: yes
      ONCLUSIVEML_TRACKING_BACKEND_ENVIRONMENT: prod
      ONCLUSIVEML_SERVING_UVICORN_APP: src.serve.__main__:model_server
      ONCLUSIVEML_SERVING_UVICORN_RELOAD: true
      ONCLUSIVEML_SERVING_UVICORN_RELOAD_DIRS: src/serve/
      ONCLUSIVEML_SERVING_UVICORN_WORKERS: 1
      NEURON_RT_NUM_CORES: 1
      ONCLUSIVEML_SERVING_UVICORN_PORT: 8000
      ONCLUSIVEML_SERVING_API_VERSION: v1
      ONCLUSIVEML_TRACKING_LOGGER_LEVEL: 10 # 10=DEBUG
      NEPTUNE_PROJECT: onclusive/iptc-20000763
      NEPTUNE_MODEL_ID: IPTC-COMPILED
      NEPTUNE_MODEL_VERSION_ID: IP20000763-COMPILED-2
      IPTC_MODEL_NAME: iptc-20000763
      COMPILED_PROJECT: onclusive/iptc-20000763
      COMPILED_MODEL: IP20000763-COMPILED
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      ONCLUSIVEML_NEPTUNE_API_TOKEN: ${NEPTUNE_API_TOKEN}
    profiles: [serve, functional]
    command:
      - /bin/sh
      - -c
      - |
        python -m src.download
        python -m src.serve.__main__
    ports:
      - 8004:8000
    hostname: onclusiveml
    networks:
      - onclusive-net
    healthcheck:
      test: [CMD, curl, -f, http://serve-iptc-20000763:8000/iptc-20000763/v1/ready]
      interval: 15s
      retries: 5
      start_period: 10s
      timeout: 30s

networks:
  onclusive-net:

volumes :
  serve-volume:
