---
version : '3.9'

services:
  # =============================================
  # SERVE
  # =============================================

  # serving image
  serve:
    volumes:
      - type: bind
        source: serve
        target: /projects/iptc-multi/serve
    build:
      context: ../../
      dockerfile: projects/iptc-multi/serve/Dockerfile
      target: ${TARGET_BUILD_STAGE:-development}
      network: host
      args:
        AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID:-690763002009}
        PROJECT: iptc-multi
        COMPONENT: serve
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG:-v23.11.3}
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-1.amazonaws.com/iptc-multi-serve:${IMAGE_TAG}
    command: [python, -m, src.serve.__main__]
    environment:
      ONCLUSIVEML_SERVING_LOGCONFIG_SERVICE: iptc-multi-serve
      ONCLUSIVEML_SERVING_LOGCONFIG_LEVEL: 10
      ONCLUSIVEML_SERVING_LOGCONFIG_JSON_FORMAT: false
      ENVIRONMENT: dev
      DOCS_URL: /iptc-multi/docs
      ONCLUSIVEML_SERVING_UVICORN_APP: src.serve.__main__:model_server
      ONCLUSIVEML_SERVING_UVICORN_RELOAD: true
      ONCLUSIVEML_SERVING_UVICORN_RELOAD_DIRS: src/serve/
      ONCLUSIVEML_SERVING_UVICORN_WORKERS: 1
      ONCLUSIVEML_SERVING_UVICORN_PORT: 8000
      ONCLUSIVEML_SERVING_API_VERSION: v1
      PROMETHEUS_MULTIPROC_DIR: /tmp
      ONCLUSIVEML_SERVING_BETTERSTACK_ENABLE: true
      ONCLUSIVEML_SERVING_BETTERSTACK_API_TOKEN: ${ONCLUSIVEML_SERVING_BETTERSTACK_API_TOKEN}
      ONCLUSIVEML_SERVING_BETTERSTACK_ENABLE_MULTI_MODEL_CHECK: true
    env_file: serve/config/dev.env
    profiles: [serve, functional]
    ports:
      - 8000:8000
    hostname: onclusiveml
    networks:
      - onclusive-net
    healthcheck:
      test: [CMD, curl, -f, http://serve:8000/iptc-multi/v1/live]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  serve-debug:
    build:
      context: ../../
      dockerfile: projects/iptc-multi/serve/Dockerfile
      target: ${TARGET_BUILD_STAGE:-debugger}
      network: host
      args:
        AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID:-690763002009}
        PROJECT: iptc-multi
        COMPONENT: serve
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG:-v23.11.3}
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-1.amazonaws.com/iptc-multi-serve:${IMAGE_TAG}
    environment:
      ONCLUSIVEML_SERVING_LOGCONFIG_SERVICE: iptc-multi-serve
      ONCLUSIVEML_SERVING_LOGCONFIG_LEVEL: 10
      ONCLUSIVEML_SERVING_LOGCONFIG_JSON_FORMAT: false
      ENVIRONMENT: dev
      DOCS_URL: /iptc-multi/docs
      ONCLUSIVEML_SERVING_UVICORN_APP: src.serve.__main__:model_server
      ONCLUSIVEML_SERVING_UVICORN_RELOAD: true
      ONCLUSIVEML_SERVING_UVICORN_RELOAD_DIRS: src/serve/
      ONCLUSIVEML_SERVING_UVICORN_WORKERS: 1
      ONCLUSIVEML_SERVING_UVICORN_PORT: 8000
      ONCLUSIVEML_SERVING_API_VERSION: v1
      ONCLUSIVEML_SERVING_BETTERSTACK_ENABLE: true
      ONCLUSIVEML_SERVING_BETTERSTACK_API_TOKEN: ${ONCLUSIVEML_SERVING_BETTERSTACK_API_TOKEN}
      ONCLUSIVEML_SERVING_BETTERSTACK_ENABLE_MULTI_MODEL_CHECK: true
    env_file: serve/config/dev.env
    profiles: [debug]
    command: [python, -m, debugpy, --listen, 0.0.0.0:5678, --wait-for-client, -m, src.serve.__main__]
    ports:
      - 5678:5678
      - 8000:8000
    hostname: onclusiveml
    networks:
      - onclusive-net
    depends_on:
      serve-iptc-00000000:
        condition: service_healthy
      serve-iptc-02000000:
        condition: service_healthy
      serve-iptc-20000082:
        condition: service_healthy
      serve-iptc-20000121:
        condition: service_healthy
    healthcheck:
      test: [CMD, curl, -f, http://serve-debug:8000/iptc-multi/v1/live]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s

  serve-iptc-00000000:
    devices:
      - /dev/neuron0:/dev/neuron0
    volumes:
      - type: bind
        source: ${HOME}/data
        target: /projects/iptc/serve/models
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-1.amazonaws.com/iptc-serve:${IMAGE_TAG}
    environment:
      ONCLUSIVEML_SERVING_LOGCONFIG_SERVICE: iptc-serve
      ONCLUSIVEML_SERVING_LOGCONFIG_LEVEL: 10
      ONCLUSIVEML_SERVING_LOGCONFIG_JSON_FORMAT: false
      ONCLUSIVEML_SERVING_MODEL_DIRECTORY: models/IP00000000-COMPILED-4
      ONCLUSIVEML_SERVING_UVICORN_APP: src.serve.__main__:model_server
      ONCLUSIVEML_SERVING_UVICORN_RELOAD: true
      ONCLUSIVEML_SERVING_UVICORN_RELOAD_DIRS: src/serve/
      ONCLUSIVEML_SERVING_UVICORN_WORKERS: 1
      NEURON_RT_NUM_CORES: 1
      ONCLUSIVEML_SERVING_UVICORN_PORT: 8000
      ONCLUSIVEML_SERVING_API_VERSION: v1
      ONCLUSIVEML_TRACKING_LOGGER_LEVEL: 10 # 10=DEBUG
      NEPTUNE_PROJECT: onclusive/iptc-00000000
      NEPTUNE_MODEL_ID: IPTC-COMPILED
      NEPTUNE_MODEL_VERSION_ID: IP00000000-COMPILED-4
      IPTC_MODEL_NAME: iptc-00000000
      COMPILED_PROJECT: onclusive/iptc-00000000
      COMPILED_MODEL: IP00000000-COMPILED
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      NEPTUNE_API_TOKEN: ${NEPTUNE_API_TOKEN}
    profiles: [debug]
    command:
      - /bin/sh
      - -c
      - |
        python -m src.download
        python -m src.serve.__main__
    ports:
      - 8001:8000
    hostname: onclusiveml
    networks:
      - onclusive-net
    healthcheck:
      test: [CMD, curl, -f, http://serve-iptc-00000000:8000/iptc-00000000/v1/ready]
      interval: 15s
      retries: 5
      start_period: 10s
      timeout: 30s

  serve-iptc-02000000:
    devices:
      - /dev/neuron1:/dev/neuron1
    volumes:
      - type: bind
        source: ${HOME}/data
        target: /projects/iptc/serve/models
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-1.amazonaws.com/iptc-serve:${IMAGE_TAG}
    environment:
      ONCLUSIVEML_SERVING_LOGCONFIG_SERVICE: iptc-serve
      ONCLUSIVEML_SERVING_LOGCONFIG_LEVEL: 10
      ONCLUSIVEML_SERVING_LOGCONFIG_JSON_FORMAT: false
      ONCLUSIVEML_SERVING_MODEL_DIRECTORY: models/IP02000000-COMPILED-18
      ONCLUSIVEML_SERVING_UVICORN_APP: src.serve.__main__:model_server
      ONCLUSIVEML_SERVING_UVICORN_RELOAD: true
      ONCLUSIVEML_SERVING_UVICORN_RELOAD_DIRS: src/serve/
      ONCLUSIVEML_SERVING_UVICORN_WORKERS: 1
      NEURON_RT_NUM_CORES: 1
      ONCLUSIVEML_SERVING_UVICORN_PORT: 8000
      ONCLUSIVEML_SERVING_API_VERSION: v1
      ONCLUSIVEML_TRACKING_LOGGER_LEVEL: 10 # 10=DEBUG
      NEPTUNE_PROJECT: onclusive/iptc-02000000
      NEPTUNE_MODEL_ID: IPTC-COMPILED
      NEPTUNE_MODEL_VERSION_ID: IP02000000-COMPILED-18
      IPTC_MODEL_NAME: iptc-02000000
      COMPILED_PROJECT: onclusive/iptc-02000000
      COMPILED_MODEL: IP02000000-COMPILED
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      NEPTUNE_API_TOKEN: ${NEPTUNE_API_TOKEN}
    profiles: [debug]
    command:
      - /bin/sh
      - -c
      - |
        python -m src.download
        python -m src.serve.__main__
    ports:
      - 8002:8000
    hostname: onclusiveml
    networks:
      - onclusive-net
    healthcheck:
      test: [CMD, curl, -f, http://serve-iptc-02000000:8000/iptc-02000000/v1/ready]
      interval: 15s
      retries: 5
      start_period: 10s
      timeout: 30s

  serve-iptc-20000082:
    devices:
      - /dev/neuron2:/dev/neuron2
    volumes:
      - type: bind
        source: ${HOME}/data
        target: /projects/iptc/serve/models
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-1.amazonaws.com/iptc-serve:${IMAGE_TAG}
    environment:
      ONCLUSIVEML_SERVING_LOGCONFIG_SERVICE: iptc-serve
      ONCLUSIVEML_SERVING_LOGCONFIG_LEVEL: 10
      ONCLUSIVEML_SERVING_LOGCONFIG_JSON_FORMAT: false
      ONCLUSIVEML_SERVING_MODEL_DIRECTORY: models/IP20000082-COMPILED-5
      ONCLUSIVEML_SERVING_UVICORN_APP: src.serve.__main__:model_server
      ONCLUSIVEML_SERVING_UVICORN_RELOAD: true
      ONCLUSIVEML_SERVING_UVICORN_RELOAD_DIRS: src/serve/
      ONCLUSIVEML_SERVING_UVICORN_WORKERS: 1
      NEURON_RT_NUM_CORES: 1
      ONCLUSIVEML_SERVING_UVICORN_PORT: 8000
      ONCLUSIVEML_SERVING_API_VERSION: v1
      ONCLUSIVEML_TRACKING_LOGGER_LEVEL: 10 # 10=DEBUG
      NEPTUNE_PROJECT: onclusive/iptc-20000082
      NEPTUNE_MODEL_ID: IP20000082-COMPILED
      NEPTUNE_MODEL_VERSION_ID: IP20000082-COMPILED-5
      IPTC_MODEL_NAME: iptc-20000082
      COMPILED_PROJECT: onclusive/iptc-20000082
      COMPILED_MODEL: IP20000082-COMPILED
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      NEPTUNE_API_TOKEN: ${NEPTUNE_API_TOKEN}
    profiles: [debug]
    command:
      - /bin/sh
      - -c
      - |
        python -m src.download
        python -m src.serve.__main__
    ports:
      - 8003:8000
    hostname: onclusiveml
    networks:
      - onclusive-net
    healthcheck:
      test: [CMD, curl, -f, http://serve-iptc-20000082:8000/iptc-20000082/v1/ready]
      interval: 15s
      retries: 5
      start_period: 10s
      timeout: 30s


  serve-iptc-20000121:
    devices:
      - /dev/neuron3:/dev/neuron3
    volumes:
      - type: bind
        source: ${HOME}/data
        target: /projects/iptc/serve/models
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-1.amazonaws.com/iptc-serve:${IMAGE_TAG}
    environment:
      ONCLUSIVEML_SERVING_LOGCONFIG_SERVICE: iptc-serve
      ONCLUSIVEML_SERVING_LOGCONFIG_LEVEL: 10
      ONCLUSIVEML_SERVING_LOGCONFIG_JSON_FORMAT: false
      ONCLUSIVEML_SERVING_MODEL_DIRECTORY: models/IP02000000-COMPILED-18
      ONCLUSIVEML_SERVING_UVICORN_APP: src.serve.__main__:model_server
      ONCLUSIVEML_SERVING_UVICORN_RELOAD: true
      ONCLUSIVEML_SERVING_UVICORN_RELOAD_DIRS: src/serve/
      ONCLUSIVEML_SERVING_UVICORN_WORKERS: 1
      NEURON_RT_NUM_CORES: 1
      ONCLUSIVEML_SERVING_UVICORN_PORT: 8000
      ONCLUSIVEML_SERVING_API_VERSION: v1
      ONCLUSIVEML_TRACKING_LOGGER_LEVEL: 10 # 10=DEBUG
      NEPTUNE_PROJECT: onclusive/iptc-02000000
      NEPTUNE_MODEL_ID: IPTC-COMPILED
      NEPTUNE_MODEL_VERSION_ID: IP02000000-COMPILED-18
      IPTC_MODEL_NAME: iptc-02000000
      COMPILED_PROJECT: onclusive/iptc-20000121
      COMPILED_MODEL: IP02000000-COMPILED
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      NEPTUNE_API_TOKEN: ${NEPTUNE_API_TOKEN}
    profiles: [debug]
    command:
      - /bin/sh
      - -c
      - |
        python -m src.download
        python -m src.serve.__main__
    ports:
      - 8004:8000
    hostname: onclusiveml
    networks:
      - onclusive-net
    healthcheck:
      test: [CMD, curl, -f, http://serve-iptc-20000121:8000/iptc-02000000/v1/ready]
      interval: 15s
      retries: 5
      start_period: 10s
      timeout: 30s


  # unit tests
  serve-unit:
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-1.amazonaws.com/iptc-multi-serve:${IMAGE_TAG}
    command: [pytest, tests/unit, -ra, -vv, --capture=no]
    volumes:
      - type: bind
        source: serve
        target: /projects/iptc-multi/serve
    profiles: [unit]
    environment:
      ENVIRONMENT: dev
    hostname: onclusiveml
    networks:
      - onclusive-net

  # integration tests
  serve-integration:
    volumes:
      - type: bind
        source: serve
        target: /projects/iptc-multi/serve
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-1.amazonaws.com/iptc-multi-serve:${IMAGE_TAG}
    command: [pytest, tests/integration, -ra, -vv, --capture=no]
    profiles: [integration]
    environment:
      ONCLUSIVEML_SERVING_UVICORN_PORT: 8000
      ONCLUSIVEML_SERVING_API_VERSION: v1
    hostname: onclusiveml
    networks:
      - onclusive-net

  # functional tests
  # - include REST model server process
  serve-functional:
    volumes:
      - type: bind
        source: serve
        target: /projects/iptc-multi/serve
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-1.amazonaws.com/iptc-multi-serve:${IMAGE_TAG}
    command: [pytest, tests/functional, -ra, -vv, --capture=no]
    environment:
      ONCLUSIVEML_SERVING_UVICORN_PORT: 8000
      ONCLUSIVEML_SERVING_API_VERSION: v1
    profiles: [functional]
    hostname: onclusiveml
    networks:
      - onclusive-net
    depends_on:
      serve:
        condition: service_healthy

networks:
  onclusive-net:
