CANDIDATE_DICT_FIRST = {
    "root": {
        "0": {
            "name": "arts, culture, entertainment and media",
            "description": "All forms of arts, entertainment, cultural heritage and media",
        },
        "1": {
            "name": "conflict, war and peace",
            "description": "Acts of socially or politically motivated protest or violence, military activities, geopolitical conflicts, as well as resolution efforts",  # noqa: E501
        },
        "2": {
            "name": "crime, law and justice",
            "description": "The establishment and/or statement of the rules of behaviour in society, the enforcement of these rules, breaches of the rules, the punishment of offenders and the organisations and bodies involved in these activities",  # noqa: E501
        },
        "3": {
            "name": "disaster, accident and emergency incident",
            "description": "Man made or natural event resulting in loss of life or injury to living creatures and/or damage to inanimate objects or property",  # noqa: E501
        },
        "4": {
            "name": "economy, business and finance",
            "description": "All matters concerning the planning, production and exchange of wealth.",  # noqa: E501
        },
        "5": {
            "name": "education",
            "description": "All aspects of furthering knowledge, formally or informally",
        },
        "6": {
            "name": "environment",
            "description": "All aspects of protection, damage, and condition of the ecosystem of the planet earth and its surroundings.",  # noqa: E501
        },
        "7": {
            "name": "health",
            "description": "All aspects of physical and mental well-being",
        },
        "8": {
            "name": "human interest",
            "description": "Item that discusses individuals, groups, animals, plants or other objects in an emotional way",  # noqa: E501
        },
        "9": {
            "name": "labour",
            "description": "Social aspects, organisations, rules and conditions affecting the employment of human effort for the generation of wealth or provision of services and the economic support of the unemployed.",  # noqa: E501
        },
        "10": {
            "name": "lifestyle and leisure",
            "description": "Activities undertaken for pleasure, relaxation or recreation outside paid employment, including eating and travel.",  # noqa: E501
        },
        "11": {
            "name": "politics",
            "description": "Local, regional, national and international exercise of power, or struggle for power, and the relationships between governing bodies and states.",  # noqa: E501
        },
        "12": {
            "name": "religion",
            "description": "Belief systems, institutions and people who provide moral guidance to followers",  # noqa: E501
        },
        "13": {
            "name": "science and technology",
            "description": "All aspects pertaining to human understanding of, as well as methodical study and research of natural, formal and social sciences, such as astronomy, linguistics or economics",  # noqa: E501
        },
        "14": {
            "name": "society",
            "description": "The concerns, issues, affairs and institutions relevant to human social interactions, problems and welfare, such as poverty, human rights and family planning",  # noqa: E501
        },
        "15": {
            "name": "sport",
            "description": "Competitive activity or skill that involves physical and/or mental effort and organisations and bodies involved in these activities",  # noqa: E501
        },
        "16": {
            "name": "weather",
            "description": "The study, prediction and reporting of meteorological phenomena",
        },
    }
}

CANDIDATE_DICT_SECOND = {
    "arts, culture, entertainment and media": {
        "0": {
            "name": "arts and entertainment",
            "description": "All forms of arts and entertainment",
        },
        "1": {
            "name": "culture",
            "description": "The ideas, customs, arts, traditions of a particular group of persons",
        },
        "2": {"name": "mass media", "description": "Media addressing a large audience"},
    },
    "conflict, war and peace": {
        "0": {
            "name": "act of terror",
            "description": "Act of violence, often resulting in casualties, designed to raise fear and anxiety in a population",
        },
        "1": {
            "name": "armed conflict",
            "description": "Disputes between opposing groups involving the use of weapons, but not necessarily formally declared wars",
        },
        "2": {
            "name": "civil unrest",
            "description": "Rallies, strikes, demonstrations, riots or other disturbances by a population, often in protest to a government or other organization's policies or actions",
        },
        "3": {
            "name": "coup d'etat",
            "description": "The overthrow of an established government by an organised military or political group",
        },
        "4": {
            "name": "massacre",
            "description": "The mass killing of people, usually civilians, during wartime hostilities",
        },
        "5": {
            "name": "peace process",
            "description": "Organized actions to end a war or conflict, usually involving peace negotiations and agreements",
        },
        "6": {
            "name": "post-war reconstruction",
            "description": "Actions to rebuild a society, economy or political system in an area affected by war",
        },
    },
    "crime, law and justice": {
        "0": {
            "name": "crime",
            "description": "Violations of laws by individuals, companies or organisations",
        },
        "1": {"name": "judiciary", "description": "The system of courts of law"},
        "2": {"name": "law", "description": "The codification of rules of behaviour"},
        "3": {
            "name": "law enforcement",
            "description": "Agencies that attempt to prevent disobedience to established laws or bring to justice those who disobey those laws",
        },
    },
    "disaster, accident and emergency incident": {
        "0": {
            "name": "accident and emergency incident",
            "description": "A sudden, unexpected event that causes unwanted consequences or requires immediate action",
        },
        "1": {
            "name": "disaster",
            "description": "A sudden, unplanned event that causes great damage or loss of life, such as an accident or a natural catastrophe",
        },
        "2": {
            "name": "emergency response",
            "description": "The planning and efforts made by people and organizations to help victims of a sudden, unplanned event, natural disaster or crisis",
        },
    },
    "economy, business and finance": {
        "0": {
            "name": "business information",
            "description": "Information about individual business entities, including companies, corporations, charities",
        },
        "1": {
            "name": "economy",
            "description": "Production, consumption, distribution and trade activities affecting regions or countries as a whole",
        },
        "2": {
            "name": "market and exchange",
            "description": "Market for buying and selling stocks, currencies, commodities and other goods",
        },
    },
    "education": {
        "0": {
            "name": "school",
            "description": "A building or institution in which education is provided",
        }
    },
    "environment": {
        "0": {
            "name": "climate change",
            "description": "Significant change in measures of climate (such as temperature, precipitation, or wind) lasting for an extended period",
        },
        "1": {
            "name": "conservation",
            "description": "Preservation of wilderness areas, flora and fauna, including species extinction",
        },
        "2": {
            "name": "environmental pollution",
            "description": "Corruption of air, water, land etc. by harmful substances",
        },
        "3": {
            "name": "natural resources",
            "description": "Environmental issues related to the exploitation of natural resources",
        },
        "4": {"name": "nature", "description": "The natural world in its entirety"},
    },
    "health": {
        "0": {
            "name": "disease and condition",
            "description": "Any health conditions affecting humans",
        },
        "1": {
            "name": "government health care",
            "description": "Health care provided by governments at any level",
        },
        "2": {
            "name": "health facility",
            "description": "Facilities used for any kind of health care",
        },
        "3": {
            "name": "health insurance",
            "description": "Insurance covering medical costs",
        },
        "4": {
            "name": "health treatment and procedure",
            "description": "Remedies, therapies, interventions, medications, testing and treatments to prevent, diagnose, manage or improve a health condition",
        },
        "5": {
            "name": "medical profession",
            "description": "Profession requiring formal training in the study, diagnosis, treatment, care and prevention of disease, medical condition or injury",
        },
    },
    "labour": {
        "0": {
            "name": "employment",
            "description": "The state of having work, usually paid, for a company, organisation, or individual",
        },
        "1": {
            "name": "labour relations",
            "description": "The relationship between workers and employers",
        },
        "2": {"name": "retirement", "description": "The years after work"},
        "3": {
            "name": "unemployment",
            "description": "The state of being available to work but not having a job",
        },
    },
    "lifestyle and leisure": {
        "0": {
            "name": "leisure",
            "description": "Activities carried out in ones' spare time and not in a competitive way.",
        },
        "1": {
            "name": "lifestyle",
            "description": "The way in which a person lives, including their style and possessions",
        },
    },
    "politics": {
        "0": {
            "name": "election",
            "description": "The selection of representatives by the casting of votes",
        },
        "1": {
            "name": "fundamental rights",
            "description": "The political, social and economic rights to which all creatures are entitled, usually upheld by law.",
        },
        "2": {"name": "government", "description": "The system for ruling a country"},
        "3": {
            "name": "government policy",
            "description": "An overall plan or course of action set out by a government intended to influence and guide decisions and actions towards a desired outcome.",
        },
        "4": {
            "name": "international relations",
            "description": "Non-violent relations between nations through negotiation, treaty, or personal meetings",
        },
        "5": {
            "name": "political process",
            "description": "The art or science of participating in the affairs of government, a state of political party",
        },
    },
    "religion": {
        "0": {
            "name": "belief systems",
            "description": "A set of beliefs prescribed by an institution or text often focusing on the worship of a higher power and the outlining of moral guidelines",
        },
        "1": {
            "name": "religious facility",
            "description": "Any facility where a group carries out its religious rites",
        },
        "2": {
            "name": "religious text",
            "description": "Texts regarded as holy or important by a religion",
        },
    },
    "science and technology": {
        "0": {
            "name": "biomedical science",
            "description": "The application of biology-based science to medical fields such as research, health monitoring or medical treatment",
        },
        "1": {
            "name": "mathematics",
            "description": "The study of structure, space, change and number in abstract, often using symbolic logic and language, and including subjects such as geometry, algebra or trigonometry",
        },
        "2": {
            "name": "natural science",
            "description": "The sciences that deal with matter, energy and the physical world, including physics, biology, chemistry and astronomy",
        },
        "3": {
            "name": "scientific research",
            "description": "The scientific and methodical investigation of events, procedures and interactions to explain why they occur, or to find solutions for problems",
        },
        "4": {
            "name": "social sciences",
            "description": "The study of human society in such aspects as linguistics, anthropology, economics or sociology",
        },
        "5": {
            "name": "technology and engineering",
            "description": "The study and practice of industrial or applied sciences such as physics, hydrodynamics or thermodynamics",
        },
        "6": {
            "name": "mechanical engineering",
            "description": "The study and application of the design, construction and operation of mechanical systems",
        },
    },
    "society": {
        "0": {
            "name": "communities",
            "description": "A group of individuals actively sharing a common value or interest",
        },
        "1": {
            "name": "demographics",
            "description": "The study of human populations and their characteristics, for example statistics or trends around aging populations in a particular geographic region",
        },
        "2": {
            "name": "discrimination",
            "description": "Unfair treatment of, or policies or practices against, individuals or groups of people on the basis of real or perceived membership in a group, such as race, sexual orientation, political or religious beliefs, age or height",
        },
        "3": {
            "name": "family",
            "description": "A group of people related genetically or by a legal bond, or who consider themselves part of a familial unit regardless of genetic or legal status",
        },
        "4": {
            "name": "mankind",
            "description": "Human beings taken as a whole, or described as members of particular groups such as teenagers, women, or people with disabilities",
        },
        "5": {
            "name": "social condition",
            "description": "The circumstances or state of affairs affecting a person's life, welfare and relations with others in a society",
        },
        "6": {
            "name": "social problem",
            "description": "Issues related to human rights, human welfare and other areas of societal concern",
        },
        "7": {
            "name": "values",
            "description": "A person's or group's principles or standards of behaviour, which guide their way of living and choices made",
        },
        "8": {
            "name": "welfare",
            "description": "Help for those in need of food, housing, health and other services",
        },
    },
    "sport": {
        "0": {
            "name": "competition discipline",
            "description": "Different types of sport which can be executed in competitions",
        },
        "1": {
            "name": "drug use in sport",
            "description": "Drug use associated with sport activities, including doping, abuse, testing and permitted medical uses",
        },
    },
    "weather": {
        "0": {
            "name": "weather forecast",
            "description": "The long- or short-term meteorological prediction and reporting of the upcoming weather for a given region",
        },
        "1": {
            "name": "weather warning",
            "description": "Alerts issued to the public about severe or notable weather in their area",
        },
    },
}


CANDIDATE_DICT_THIRD = {'economic sector': {'0': {'name': 'agriculture',
   'description': 'The growing and raising of plants and animals for consumption and the processing, cleaning, packing or storage of these products'},
  '1': {'name': 'chemicals',
   'description': 'Natural or manmade materials used to produce other materials'},
  '2': {'name': 'computing and information technology',
   'description': 'Computers and the transmission of information'},
  '3': {'name': 'construction and property',
   'description': 'All items pertaining to the construction and sale of property'},
  '4': {'name': 'consumer goods',
   'description': 'Items produced for and sold to individuals'},
  '5': {'name': 'energy and resource',
   'description': 'The use of natural resources to generate energy'},
  '6': {'name': 'manufacturing and engineering',
   'description': 'Manufacturers of electrical, electronic and mechanical equipment but does not cover civil engineering.'},
  '7': {'name': 'transport',
   'description': 'The means of getting people or goods from one place to another'}},
 'business information': {'0': {'name': 'human resources',
   'description': 'People working for a business and how they are managed'}},
 'market and exchange': {'0': {'name': 'foreign exchange market',
   'description': 'The market for international currency'},
  '1': {'name': 'loan market',
   'description': 'The market where financial organisations provide loans to borrowers and sell them on to investors'}},
 'disaster': {'0': {'name': 'famine',
   'description': 'Severe lack of food for a large population'},
  '1': {'name': 'fire',
   'description': 'Fires started by an accidental or unknown source. For wildfires, use wildfire. For fires started with a criminal intent, use arson.'}},
 'accident and emergency incident': {'0': {'name': 'explosion accident and incident',
   'description': 'Explosions caused by an accidental, non-combat, or non-terrorism source. Also use when the source of the explosion is non-specified or unknown'},
  '1': {'name': 'industrial accident and incident',
   'description': 'Any unplanned event or mishap in an industrial setting that result in injuries to people and damage to property or the environment'}},
 'natural science': {'0': {'name': 'astronomy',
   'description': 'The study of celestial objects through direct observation and theoretical models'},
  '1': {'name': 'biology',
   'description': 'The study of the anatomy, behaviour, origin, physiology and other aspects of living organisms'},
  '2': {'name': 'chemistry',
   'description': 'The study of the composition and properties of matter on the scale of atoms and molecules, and of the reactions between compounds'},
  '3': {'name': 'cosmology',
   'description': 'The study of the origin, evolution, organisation and structure of the universe'},
  '4': {'name': 'geology',
   'description': "The study of Earth's physical processes, material structures and its properties"},
  '5': {'name': 'horticulture',
   'description': 'The study and art of plant cultivation, including landscape and garden design and plant conservation'},
  '6': {'name': 'marine science',
   'description': 'The study of living organisms and environments in saltwater ecosystems'},
  '7': {'name': 'meteorology',
   'description': 'The study of atmospheric chemistry and physics, with a focus on weather forecasting'},
  '8': {'name': 'physics',
   'description': 'The study of the movement and structure of matter, and how it relates to energy'}},
 'technology and engineering': {'0': {'name': 'aerospace engineering',
   'description': 'The study, design, development and construction of aircraft, spacecraft and missile systems'},
  '1': {'name': 'civil engineering',
   'description': 'The study, design, development and construction of structures such as buildings, bridges, tunnels, irrigation and sewage systems, streets or railroads'},
  '2': {'name': 'electronic engineering',
   'description': 'The study, design, development and application of systems built on the exchange of electrical charges, such as consumer devices, communications systems or industrial computers'},
  '3': {'name': 'information technology and computer science',
   'description': 'The study and design of computer systems, software and networks'},
  '4': {'name': 'micro science',
   'description': 'The study of and technologies built at a microscopic scale, such as microbiology or microcomputing'}},
 'social sciences': {'0': {'name': 'anthropology',
   'description': 'The study of human behaviour and social interactions across time'},
  '1': {'name': 'archaeology',
   'description': 'The study of human activity throughout time and cultural history, using artefacts left behind by ancient peoples'},
  '2': {'name': 'economics',
   'description': 'The study of the laws and principles of economies, such as the production and distribution of goods and services'},
  '3': {'name': 'geography',
   'description': 'The study of the physical features of the surface of Earth and its political divisions'},
  '4': {'name': 'history',
   'description': 'The study of human events of the past'},
  '5': {'name': 'information science',
   'description': 'The study and practice of collecting, classifying, storing, retrieving and disseminating information'},
  '6': {'name': 'linguistics',
   'description': 'The study of all aspects of human language such as syntax, phonetics, written and spoken forms and variations over time'},
  '7': {'name': 'philosophy',
   'description': 'The study of the principles and fundamental questions about matters such as the mind, reason, morality or values'},
  '8': {'name': 'political science',
   'description': 'The study of the principles of political and governmental systems, political thought and practices'},
  '9': {'name': 'psychology',
   'description': 'The study of the human mind, mental characteristics and emotional processes'},
  '10': {'name': 'sociology',
   'description': 'The study of human social organisation, social relationships and societal changes'}},
 'scientific research': {'0': {'name': 'medical research',
   'description': 'Investigation conducted in the fields of health and medicine, such as genetic studies, disease research or pharmaceutical drug trials'},
  '1': {'name': 'scientific exploration',
   'description': 'Land, sea or space journeys undertaken to discover new information'}},
 'judiciary': {'0': {'name': 'court',
   'description': 'Place where legal cases are heard and decided'},
  '1': {'name': 'out of court procedures',
   'description': 'Legal issues which are settled outside of court'}},
 'law enforcement': {'0': {'name': 'arrest',
   'description': 'The detention of a suspect of a crime'},
  '1': {'name': 'investigation (criminal)',
   'description': 'Inquiry into an alleged crime, including searching, interviews, interrogations and evidence collection'},
  '2': {'name': 'police',
   'description': 'Civil force of a national, regional or local government that is responsible for the prevention and detection of crime and the maintenance of public order'}},
 'law': {'0': {'name': 'civil law',
   'description': 'The system of law focused on private rights and disputes between individuals in such areas as contracts, torts, property, and family law'},
  '1': {'name': 'criminal law',
   'description': 'The system of law concerned with the punishment of those who commit crimes'},
  '2': {'name': 'international law',
   'description': 'The system of laws embraced by all nations, such as the Geneva Convention and the International Law of the Seas'}},
 'crime': {'0': {'name': 'arson',
   'description': 'The intentional setting of fires with criminal intent'},
  '1': {'name': 'assault',
   'description': 'Physical crime against a person, including battery, brawls and threat of bodily harm'},
  '2': {'name': 'corporate crime',
   'description': 'Crimes committed by a corporation or by individuals acting on behalf of a corporation'},
  '3': {'name': 'corruption',
   'description': 'Dishonest actions by a person in power in return for pecuniary or personal gain'},
  '4': {'name': 'drug related crimes',
   'description': 'Illegal activities involving illicit substances, including buying, distribution, selling and smuggling'},
  '5': {'name': 'fraud',
   'description': 'Intentional deception for personal or financial gain'},
  '6': {'name': 'hijacking',
   'description': 'Taking over a transportation vehicle by force'},
  '7': {'name': 'homicide',
   'description': 'The killing of one person by another, including murder and manslaughter'},
  '8': {'name': 'kidnapping',
   'description': "To seize and detain a person against that person's will by unlawful threat, force or fraud"},
  '9': {'name': 'organised crime',
   'description': 'Crimes committed by gangs or criminal organizations, such as the mafia'},
  '10': {'name': 'terrorism',
   'description': 'Violence against people to create fear in order to achieve political or ideological objectives'},
  '11': {'name': 'war crime',
   'description': 'Crimes committed during a war or armed conflict, usually against civilians or prisoners of war, including the prosecution of such crimes'}},
 'health treatment and procedure': {'0': {'name': 'diet',
   'description': 'Ways of eating to benefit health or treat a condition, such as plant-based, low-salt, high-fibre or gluten-free'},
  '1': {'name': 'therapy',
   'description': 'Treatment of physical, mental or medical conditions by non-surgical means'}},
 'disease and condition': {'0': {'name': 'cancer',
   'description': 'A serious and often fatal disease caused when normal cells mutate into tumours'},
  '1': {'name': 'communicable disease',
   'description': 'Diseases that can be transmitted from one person or animal to another'},
  '2': {'name': 'heart disease',
   'description': 'Diseases and conditions affecting the heart such as heart attacks, the narrowing of arteries, arrhythmia or cardiomyopathy'},
  '3': {'name': 'injury',
   'description': 'Harm caused to the human body by external forces such as falls, weapons or accidents'},
  '4': {'name': 'obesity',
   'description': 'A condition of body weight generally considered 20 percent above the norm for gender, age, height and bone structure'}},
 'non-human diseases': {'0': {'name': 'animal disease',
   'description': 'Disease affecting animals'},
  '1': {'name': 'plant disease',
   'description': 'Disorders affecting plants caused either by parasites or environmental factors'}},
 'leisure': {'0': {'name': 'club and association',
   'description': 'Organisations joined by individuals because of similar interests'},
  '1': {'name': 'game',
   'description': "Contests generally for one's amusement"},
  '2': {'name': 'gaming and lottery',
   'description': 'Gambling, often involving selection of sets of numbers one expects to come up'},
  '3': {'name': 'hobby', 'description': 'Recreational pursuit'},
  '4': {'name': 'holiday',
   'description': 'Time spent not at work for rest and relaxation'},
  '5': {'name': 'leisure venue',
   'description': 'A place where people go to be entertained or amused. For sporting events, use sport venue.'}},
 'lifestyle': {'0': {'name': 'house and home',
   'description': "Interest in maintaining and decorating one's home"},
  '1': {'name': 'party',
   'description': 'A social gathering of invited guests, often involving eating, drinking, dancing or the playing of games'},
  '2': {'name': 'trend',
   'description': 'Interest in what is considered hip or popular at a certain point in time'}},
 'armed conflict': {'0': {'name': 'military occupation',
   'description': 'The temporary forceful taking over of a country or region by invading military forces'},
  '1': {'name': 'war',
   'description': 'Armed hostilities by one group or geopolitical entity against another'}},
 'civil unrest': {'0': {'name': 'demonstration',
   'description': 'A non-violent public show of support for or opposition to a cause, idea or policy, in the form of a mass meeting or march'},
  '1': {'name': 'rebellion',
   'description': "Organized actions of opposition to a government or ruling party by a country's residents, often violent and with the aim of overthrowing the government"},
  '2': {'name': 'revolution',
   'description': "A forcible and often violent change to, or overthrow of, a country's political system or social order by internal forces, in favour of a new system"},
  '3': {'name': 'riot',
   'description': 'Violent, destructive events of civil disorder by groups of people, usually in response to a grievance or as acts of opposition, often involving injury to individuals and destruction of property'}},
 'act of terror': {'0': {'name': 'act of bioterrorism',
   'description': 'Attacks using biological agents intended to raise the level of fear within a population'}},
 'competition discipline': {'0': {'name': 'American football',
   'description': 'Team ball game that opposes two teams of 11 that have offence and defence sections. Each offence attempts to move an oval ball down the 120 yards long field. Points are scored by advancing the ball into the opposing team s end zone.'},
  '1': {'name': 'Australian rules football',
   'description': 'A form of football played by two teams of 18 competing on a pitch by running with and passing an oval ball. Points are scored by moving the ball between goal posts. Governed by the Australian Football League.'},
  '2': {'name': 'Jai Alai (Pelota)',
   'description': 'A fast ball play using either the bare hand or a wicker scoop in an arena of walls of different outlay and size'},
  '3': {'name': 'archery',
   'description': 'Archers use bows and arrows to aim at targets 1.22 metres in diameter which are on average 70 metres distant.'},
  '4': {'name': 'badminton',
   'description': 'Two players or two teams of two compete by hitting a shuttlecock weighing approximately five grams over a high net. The aim for each player/team is to prevent the shuttlecock landing on their side of the court.'},
  '5': {'name': 'bandy',
   'description': 'Played outdoors on ice. The size of the ice rink is about the size of a soccer field. Skates like ice hockey. A small hard ball is used for playing. Players play with sticks, much like in ice hockey, but the sticks are shorter and more rounded than in ice'},
  '6': {'name': 'baseball',
   'description': 'A game between two teams of nine played on an enclosed ground. The team which scores the most points wins. A point is scored when a player runs around the ground marked out by four bases. To do this he has to hit the ball thrown at him by a rival player.'},
  '7': {'name': 'basketball',
   'description': 'Game played between two teams of five - points are scored by placing the large inflated ball into a net fixed on a ring 3.05m above the ground.'},
  '8': {'name': 'biathlon',
   'description': 'A combination of cross-country skiing and target shooting on a 12.5 K course in a pursuit format.'},
  '9': {'name': 'billiards',
   'description': 'A cue sport with balls on a table without a specific order to play them'},
  '10': {'name': 'bobsleigh',
   'description': 'One, two or four people racing down a course in a sled that consists of a main hull, a frame, two axles and sets of runners. The total time of all heats in a competition is added together to determine the winner.'},
  '11': {'name': 'boxing',
   'description': 'Combat sport in which two men/women fight using only their fists covered by padded gloves in a square ring measuring 6m a side. The fight is usually split into 12 rounds of three minutes each.'},
  '12': {'name': 'bullfighting',
   'description': 'Classical contest pitting man against the bull'},
  '13': {'name': 'canoeing',
   'description': 'Competition involving canoes which are generally kneeled and paddled with a single-bladed paddle'},
  '14': {'name': 'chess',
   'description': 'Competition between two players using a chequered board with 16 pieces to each side, each with specific ranges of movement depending on their identity'},
  '15': {'name': 'cricket',
   'description': "Ball sport involving two teams of 11 players, balls, bats and wickets. The aim is to score as many runs as possible, and to get the opposing team 'out'. A 'run' involves a player running between two wickets. The opposing team try to get their rivals 'out'"},
  '16': {'name': 'curling',
   'description': 'A game played on ice with large flat round stones. A player throws the stone, aiming at a target. Teammates of the player who has thrown the stone can sweep the ice in front of the stone to help smooth its path towards the target.'},
  '17': {'name': 'cycling',
   'description': 'A race over a given distance on bicycles.'},
  '18': {'name': 'darts',
   'description': 'The sport in which small darts are thrown at a dartboard, a circular target divided into numbered sections.'},
  '19': {'name': 'diving',
   'description': 'Competitors dive off a fixed or spring board and are assessed by seven judges giving marks up to ten for their acrobatic moves.'},
  '20': {'name': 'dog racing', 'description': 'Dogs racing around a track'},
  '21': {'name': 'fencing',
   'description': 'Combat sport using a sword or foil.'},
  '22': {'name': 'field hockey',
   'description': 'A ball sport involving two teams of 11 players using curved sticks. The aim is to score as many goals as possible.'},
  '23': {'name': 'figure skating',
   'description': 'To obtain the best marks possible from nine judges who award scores after two prepared sections - both skated to music - during which competitors must attempt to achieve the greatest possible harmony between artistic flair and technical precision.'},
  '24': {'name': 'floorball',
   'description': 'Played indoors in a court the size of a basketball court. 6 players per team, of which one is a goalkeeper. He/she operates kneeling but there is no goal-stick like in ice hockey. The players use plastic clubs and a light plastic ball to pass and shot goal'},
  '25': {'name': 'golf',
   'description': 'A game to hit a small hard ball with different clubs around a course of typically 18 holes varying in distance and during a round. The object, depending on the scoring formulae, is to make the fewest strokes possible'},
  '26': {'name': 'gymnastics',
   'description': 'A sport consisting of a variety of disciplines in which gymnasts perform artistic and acrobatic moves using different apparatus.'},
  '27': {'name': 'handball (team)',
   'description': 'A ball game using the hands contested by two teams of seven trying to throw the ball into the opponents goal.'},
  '28': {'name': 'horse racing', 'description': 'Mounted horse races.'},
  '29': {'name': 'hurling',
   'description': "A game played by two teams of fifteen each with a curved wooden stick called a hurley. The object is to score a goal by hitting the small ball between the opponents' goalposts either over the crossbar or under it into a net guarded by a goalkeeper."},
  '30': {'name': 'ice hockey',
   'description': 'Two teams of six heavily padded skaters try and outscore each other by hitting a puck into the opponents goal.'},
  '31': {'name': 'kabaddi',
   'description': "The attacking side scores by touching, and the side to guard scores by capturing. The attacker continues calling it 'kabaddi'."},
  '32': {'name': 'kayaking',
   'description': 'Competition involving kayaks where the paddler sits with their legs facing forward using a double-bladed paddle'},
  '33': {'name': 'lacrosse',
   'description': 'Two teams of helmeted and padded players try and outscore each other using a netted stick and hard ball.'},
  '34': {'name': 'luge',
   'description': 'Luge (French word for sled) is competed in singles or doubles. The competitor(s) lay on their back on an open sled and race down a course. The competitor(s) and the sled must be in contact when passing the finishing line. The competitor can steer the sled'},
  '35': {'name': 'marathon',
   'description': 'A road race where competitors run 42.195km, generally through city streets'},
  '36': {'name': 'martial arts',
   'description': 'Martial arts are codified systems and traditions of combat practices, which are practiced for a variety of reasons: self-defence, competition, physical health and fitness, entertainment, as well as mental, physical, and spiritual development.'},
  '37': {'name': 'modern pentathlon',
   'description': 'The Modern Pentathlon comprises five events run over a single day in the following order: shooting, fencing, swimming, horse riding and running.'},
  '38': {'name': 'motor car racing', 'description': 'Racing with cars'},
  '39': {'name': 'motorcycling',
   'description': 'Races with 2, 3 or 4 wheels vehicles with a saddle and handlebars'},
  '40': {'name': 'mountain climbing',
   'description': 'Moving up mountains using hands and feet'},
  '41': {'name': 'netball',
   'description': "A woman's sport similar to basketball though without a board behind the basket"},
  '42': {'name': 'orienteering',
   'description': 'An individual time-trial over a route marked out by beacons. The competitor has to search out and find in a specific order. The contestant makes his way with the help of a compass and map'},
  '43': {'name': 'parachuting',
   'description': 'Jumping from an aeroplane using a parachute, competitions are precision landings, voltige, individual and team'},
  '44': {'name': 'polo',
   'description': 'With the aid of a mallet two teams of four horsemen try and knock a bamboo ball into the opponents goal over a pitch 250m long and 150m wide. The game is divided into 4, 6, or 8 time periods of 7min 30sec called chukkas.'},
  '45': {'name': 'pool',
   'description': 'A cue sport on a table with pockets, played with different numbers of balls'},
  '46': {'name': 'rodeo',
   'description': 'A discipline where wild horses or bulls must be mounted and mastered'},
  '47': {'name': 'roller sports',
   'description': 'Various competitions using wheeled equipment such as roller skates, inline skates, and skateboards.'},
  '48': {'name': 'rowing',
   'description': 'Boat racing usually on flat calm waters with boats for 1, 2, 4 or 8 rowers'},
  '49': {'name': 'rugby league',
   'description': 'A type of rugby where two teams of 13 compete on a pitch by running with and passing an oval ball. Points are scored by touching down the ball behind the goal line or kicking it between goal posts. Governed by Rugby League International Federation.'},
  '50': {'name': 'rugby union',
   'description': 'A type of rugby where two teams of 15 compete on a pitch by running with and passing an oval ball. Points are scored by touching down the ball behind the goal line or kicking it between goal posts. Governed by the World Rugby organization.'},
  '51': {'name': 'sailing', 'description': 'Sailing boat racing over a route'},
  '52': {'name': 'shinty',
   'description': 'A ball game involving 2 teams with curved sticks called camans. The object is to score goals by hitting the small leather ball through the goals.'},
  '53': {'name': 'skeleton',
   'description': 'In skeleton the competitor lies on his/her stomach when racing down the course. The competitor must be on the sled when crossing the finishing line.'},
  '54': {'name': 'skiing',
   'description': 'A winter sport using different types of skis'},
  '55': {'name': 'snooker',
   'description': 'A cue sport with balls on a table to be potted in a specific order'},
  '56': {'name': 'snowboarding',
   'description': 'Practiced with a single board (rather than two skis)'},
  '57': {'name': 'soccer',
   'description': 'A form of football played by two teams competing on a pitch by kicking a spherical ball. Points are scored by kicking or heading the ball into a goal. Governed by the Fédération Internationale de Football Association'},
  '58': {'name': 'softball',
   'description': 'Similar to baseball but with a larger and softer ball, a thinner bat, shorter gaps between bases and less innings'},
  '59': {'name': 'speed skating',
   'description': 'Timed races competed by two or more skaters at a time on an oval ice track'},
  '60': {'name': 'sport shooting',
   'description': 'Precision sport using a hand gun, rifle or shotgun'},
  '61': {'name': 'squash',
   'description': 'A racquet sport of strategy and endurance played by singles or doubles teams in a walled court with a small rubber ball'},
  '62': {'name': 'sumo wrestling',
   'description': 'A combat sport of speed and rapidity with much ceremony where two contestants try to throw or slap a competitor out of a marked area. Generally practiced in Japan by large men.'},
  '63': {'name': 'surfing',
   'description': 'Water sport where contestants catch and ride waves upright on a surfboard'},
  '64': {'name': 'swimming',
   'description': 'A water sport where contestants swim as fast as possible in a given style and win races by being the first to touch home'},
  '65': {'name': 'table tennis',
   'description': 'A racquet sport for two or four (in doubles), who compete at a table divided by a net using a small bat to play a lightweight ball'},
  '66': {'name': 'tennis',
   'description': "A sport where two players, four in doubles, equipped with a racket compete by hitting the ball over a net into the opponent's side of the court with the aim of putting it out of reach within the regulation lines, thus winning points."},
  '67': {'name': 'triathlon',
   'description': 'An endurance multi-sport where competitors first swim, then cycle and then run a road race. Distances vary according to the competition.'},
  '68': {'name': 'volleyball',
   'description': "Two teams of six record points by hitting a ball over a net into the opponent's half of the court, keeping it in the air at all times. Points are won when opponents fail to return the ball."},
  '69': {'name': 'water polo',
   'description': 'Played in a pool between two teams of 7, who must stay afloat and can only use one hand to pass the ball or swim with it before trying to throw it into the opponents net to score goals.'},
  '70': {'name': 'wrestling',
   'description': 'Combat sport where each wrestler attempts to win over his adversary, by holding both shoulders on the ground (fall) long enough to be in control. Points can also be decisive.'}},
 'arts and entertainment': {'0': {'name': 'animation',
   'description': 'Stories told through animated drawings in either full-length or short format'},
  '1': {'name': 'cartoon',
   'description': 'Drawings, such as editorial cartoons and comic strips, often using humour or satire'},
  '2': {'name': 'cinema',
   'description': 'Stories told through motion pictures, such as full-length or short format documentary or fictional features'},
  '3': {'name': 'dance',
   'description': 'A form of performing art consisting of purposefully selected sequences of human movement'},
  '4': {'name': 'fashion',
   'description': 'Styles and trends in clothing, footwear, accessories, including the design, presentation and wearing of these styles and trends'},
  '5': {'name': 'literature',
   'description': 'The telling of a story through written language'},
  '6': {'name': 'music',
   'description': 'A form of performing art using instruments or voice to create different sounds, tones and harmonies'},
  '7': {'name': 'theatre',
   'description': 'A form of performing art where live performers portray a narrative to an audience through dialogue and action'},
  '8': {'name': 'opera',
   'description': 'A form of performing art where classically trained musicians and singers perform a musical and dramatic work'},
  '9': {'name': 'visual arts',
   'description': 'A form of art which appeals primarily to the visual senses, such as ceramics, drawing, painting, sculpture, printmaking, design, crafts, photography, video, filmmaking, and architecture.'},
  '10': {'name': 'art exhibition',
   'description': 'Temporary presentation of art in museums, art halls or galleries'}},
 'culture': {'0': {'name': 'language',
   'description': 'The method of human communication, either spoken or written, consisting of words that are used in a structured and conventional way'},
  '1': {'name': 'library and museum',
   'description': 'Institutions that house collections of books, music, art, or objects from the past and present optionally for public use and display'},
  '2': {'name': 'monument and heritage site',
   'description': 'Commemorations of historical people, events, or the areas containing them, in the form of structures such as sculptures, statues or buildings'}},
 'mass media': {'0': {'name': 'news media',
   'description': 'The presentation of news to the public through different platforms, such as TV, radio, newspapers, magazines, web pages and blogs'},
  '1': {'name': 'newspaper',
   'description': 'Daily or weekly publication that presents the news, locally, regionally or globally, as well as features, opinion columns, comics and other content'},
  '2': {'name': 'periodical',
   'description': 'Publication that is usually published weekly, bi-weekly, monthly or annually, such as magazines, journals or newsletters'},
  '3': {'name': 'radio',
   'description': 'Audio content, such as news, entertainment or information, distributed via broadcast or internet'},
  '4': {'name': 'television',
   'description': 'Video content, such as news, entertainment or information, distributed via broadcast or internet'}},
 'natural resources': {'0': {'name': 'renewable energy',
   'description': 'Energy derived from sustainable sources'},
  '1': {'name': 'land resources',
   'description': 'That portion of a nation or state that is above water and available for development either for profit or for the general good of the public'},
  '2': {'name': 'population growth',
   'description': 'People and their growth and development within a natural setting'},
  '3': {'name': 'water',
   'description': 'Environmental issues about bodies of water, including oceans, lakes, streams and reservoirs, as well as ice, glaciers and forms of precipitation'}},
 'environmental pollution': {'0': {'name': 'air pollution',
   'description': 'Solid or gaseous matter affecting the quality of air that we breathe'},
  '1': {'name': 'water pollution',
   'description': 'Solids or liquids that corrupt the quality of water that could be used for drinking or irrigation'}},
 'nature': {'0': {'name': 'ecosystem',
   'description': 'A system of plants, animals and bacteria interrelated in its physical/chemical environment'},
  '1': {'name': 'endangered species',
   'description': 'Those species in danger of disappearing, largely because of changes in environment, hunting, or weather'},
  '2': {'name': 'invasive species',
   'description': 'Non-native plants, animals and other organisms that tend to take over native species'}},
 'belief systems': {'0': {'name': 'Buddhism',
   'description': 'An Asian religion founded in the 6th century BC in India based on the teachings of the Buddha with the goal of overcoming suffering and transcending desire and the individual self to achieve nirvana'},
  '1': {'name': 'Christianity',
   'description': 'Religions that follow the teachings of Jesus Christ and the Bible'},
  '2': {'name': 'Confucianism',
   'description': 'A system of thought and behaviour originating in ancient China and based on the teachings of the philosopher Confucius'},
  '3': {'name': 'Hinduism',
   'description': 'A religion and social system originating in India that includes a caste system, a belief in reincarnation and the worship of multiple deities'},
  '4': {'name': 'Islam',
   'description': "Monotheistic religion that considers Muhammad as a prophet and the Qur'an as holy scripture"},
  '5': {'name': 'Jainism',
   'description': 'A religion beginning in the 7th-5th century BC in India that teaches a path to spiritual purity and enlightenment through a disciplined mode of life founded upon the tradition of ahimsa, nonviolence to all living creatures'},
  '6': {'name': 'Judaism',
   'description': 'A monotheistic religion and culture that follows the teachings of the Torah'},
  '7': {'name': 'Scientology',
   'description': 'A set of beliefs and practices invented by American science fiction author L. Ron Hubbard asserting that a human is an immortal, spiritual being (Thetan) that is resident in a physical body'},
  '8': {'name': 'Shintoism',
   'description': 'An indigenous Japanese polytheistic religion that revolves around kami, supernatural entities believed to inhabit all things'},
  '9': {'name': 'Sikhism',
   'description': 'An Indian Dharmic religion that originated at the end of the 15th century CE in the Punjab region, developed from the spiritual teachings of Guru Nanak'},
  '10': {'name': 'Taoism',
   'description': 'A philosophical and spiritual tradition originating in the 4th century BCE in China which emphasizes living in harmony with the Tao, the source, pattern and substance of everything that exists'}},
 'religious text': {'0': {'name': 'Bible',
   'description': 'Holy book of Christianity'},
  '1': {'name': "Qur'an", 'description': 'Holy book of Islam'},
  '2': {'name': 'Torah', 'description': 'Holy book of Judaism'}},
 'religious facility': {'0': {'name': 'church',
   'description': 'A building used as a place of worship for the Christian religion'},
  '1': {'name': 'mosque',
   'description': 'A building used as a place of worship for the Islamic religion'},
  '2': {'name': 'synagogue',
   'description': 'A building used as a place of worship for the Jewish religion'}},
 'government': {'0': {'name': 'civil and public service',
   'description': 'The paid service by civilians for the government, and the often non-paid service of individuals for the benefit of others (public service)'},
  '1': {'name': 'constitution (law)',
   'description': 'Usually a written document setting forth the operations of a government and the rights of the citizens therein'},
  '2': {'name': 'defence',
   'description': "Anything involving the protection of one's own country"},
  '3': {'name': 'espionage and intelligence',
   'description': 'Covert collection of information'},
  '4': {'name': 'executive (government)',
   'description': 'That portion of a ruling body involving the overall operation of government'},
  '5': {'name': 'government budget',
   'description': 'The expenses and revenues approved by the legislature.'},
  '6': {'name': 'heads of state',
   'description': 'Symbolic or actual chief representative of a nation, such as royalty, or president or emir, for example'},
  '7': {'name': 'impeachment',
   'description': 'The process of bringing a public official before a tribunal to answer charges of wrongdoing'},
  '8': {'name': 'legislative body',
   'description': 'A legislature of elected officials representing the people that has the authority to make laws'},
  '9': {'name': 'local government and authority',
   'description': 'Authorities at borough, city or county level'}},
 'election': {'0': {'name': 'electoral system',
   'description': 'Voting systems'},
  '1': {'name': 'local elections',
   'description': 'Choosing individuals for government at the basic level, whether city, village or county'},
  '2': {'name': 'political campaigns',
   'description': 'Campaigns for public office'},
  '3': {'name': 'referenda',
   'description': 'Political proposals, laws and actions suggested by non-government officials to be voted on by the entire voting body'},
  '4': {'name': 'voting',
   'description': 'The act of selecting an individual you would like to represent your interests in government'}},
 'international relations': {'0': {'name': 'diplomacy',
   'description': 'The use of verbal and written skills for persuading others to your point of view'},
  '1': {'name': 'foreign aid',
   'description': 'Help provided by one nation to another'},
  '2': {'name': 'refugees and internally displaced people',
   'description': 'A person seeking shelter in another country because of some fear of persecution in his own country'}},
 'government policy': {'0': {'name': 'economic policy',
   'description': 'Government directed policy on production, taxes, tariffs and things that affect the direction and health of the economy'},
  '1': {'name': 'migration policy',
   'description': 'Movement of one body of persons from one place to another'},
  '2': {'name': 'nuclear policy',
   'description': 'Government policies as regards to use of nuclear fuels for power production or weapons'},
  '3': {'name': 'regulation of industry',
   'description': 'The rules and bodies, both national and international, that govern conflict of interest and good practice regulations.'},
  '4': {'name': 'safety of citizens',
   'description': 'Government policies to protect the well-being of its citizens'},
  '5': {'name': 'sports policies',
   'description': 'Government policies affecting sports'},
  '6': {'name': 'taxation',
   'description': 'A levy to fund government expenditure'}},
 'fundamental rights': {'0': {'name': 'censorship and freedom of speech',
   'description': 'Attempts by any group to control freedoms of speech, religion, and ideas distributed in print, graphics, cyberspace and other ways. Does not include official standards such as cinema ratings, advertising and broadcast standards.'},
  '1': {'name': 'freedom of the press',
   'description': 'Mass media rights and freedoms, pressure and intimidation of the journalists, censorship in mass media, activities of government bodies, journalistic associations and/or organisations and other NGOs in regards to press freedom'},
  '2': {'name': 'human rights',
   'description': 'Rights entitled to be enjoyed by all citizens universally'}},
 'political process': {'0': {'name': 'lobbying',
   'description': 'The attempt by non-government bodies and individuals to affect the outcome of legislation through verbal, or other, persuasion'},
  '1': {'name': 'political parties and movements',
   'description': 'Covers both formally recognised and informal political associations'},
  '2': {'name': 'political system',
   'description': 'System designed to provide order to government'}},
 'family': {'0': {'name': 'adoption',
   'description': "The legal process of transferring parental rights to someone other than a person's birth parents, that person usually being a child"},
  '1': {'name': 'divorce',
   'description': 'The process by which a marriage is legally dissolved'},
  '2': {'name': 'family planning',
   'description': 'Services and education aimed at informing individual decisions about reproduction, such as fertility, in vitro fertilisation, contraception or abortion'},
  '3': {'name': 'marriage',
   'description': 'The legal or socially recognised union of individuals, which establishes rights and obligations between them'}},
 'values': {'0': {'name': 'death and dying',
   'description': 'Social, medical and mental health issues relating to people at the end of their lives'},
  '1': {'name': 'ethics',
   'description': 'The moral values and standards that define right and wrong actions or decisions'},
  '2': {'name': 'pornography',
   'description': 'The depiction of sexually explicit acts in various media renditions, such as video or photos, often considered obscene or immoral'}},
 'social problem': {'0': {'name': 'addiction',
   'description': 'The habitual and compulsive use of substances such as alcohol or drugs, or behaviour such as gambling, gaming or sex, often causing detrimental effects on the body, brain, and relationships with others'},
  '1': {'name': 'juvenile delinquency',
   'description': 'Unlawful conduct perpetrated by minors, often on a repeated basis'},
  '2': {'name': 'prostitution',
   'description': 'The business of engaging in sexual activity in exchange for payment'},
  '3': {'name': 'slavery',
   'description': 'The ownership of people as property, and the involuntary servitude of those people to their owners, which includes unpaid labour and coerced actions'}},
 'discrimination': {'0': {'name': 'ageism',
   'description': 'Discrimination against individuals or groups of people on the basis of age'},
  '1': {'name': 'racism',
   'description': 'Discrimination against individuals or groups of people on the basis of race'},
  '2': {'name': 'sexism',
   'description': 'Discrimination against individuals or groups of people, usually women, on the basis of gender'}},
 'social condition': {'0': {'name': 'homelessness',
   'description': 'The social condition defined by lack of permanent residence, living in shelters or on streets, and the issues and problems associated with it'},
  '1': {'name': 'poverty',
   'description': "The lack of sufficient resources and means to provide basic needs such as food, clothing or shelter for oneself and one's family"}},
 'mankind': {'0': {'name': 'children',
   'description': 'Young people, usually pre-pubescent, who are legally considered minors and are in a guardianship relationship with adults'},
  '1': {'name': 'gender',
   'description': 'The classification of individuals as male, female, or a non-binary designation'},
  '2': {'name': 'infants',
   'description': 'Very young people, usually defined as being just born up to the age of two'},
  '3': {'name': 'senior citizens',
   'description': 'People having passed the age of retirement'},
  '4': {'name': 'teenagers',
   'description': 'Young people between the ages that describe childhood and adulthood'}}}