---
version : '3.9'

services:
  # =============================================
  # SERVE
  # =============================================

  # serving image
  serve:
    build:
      context: ../../
      dockerfile: projects/entity-linking/serve/Dockerfile
      target: ${TARGET_BUILD_STAGE:-development}
      network: host
      args:
        AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID:-063759612765}
        PROJECT: entity-linking
        COMPONENT: serve
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG}
    image: ${AWS_ACCOUNT_ID:-063759612765}.dkr.ecr.us-east-1.amazonaws.com/entity-linking-serve:${IMAGE_TAG}
    profiles: [serve]
    hostname: onclusiveml
    networks:
      - onclusive-net

  # serving image
  serve-serve-model:
    image: ${AWS_ACCOUNT_ID:-063759612765}.dkr.ecr.us-east-1.amazonaws.com/entity-linking-serve:${IMAGE_TAG}
    command: [uvicorn, src.app:app, --host, 0.0.0.0, --port, '9000', --reload, --log-level, debug]
    profiles: [serve]
    ports:
      - 9000:9000
    environment:
      ENVIRONMENT: dev
      DOCS_URL: /docs
    hostname: onclusiveml
    networks:
      - onclusive-net

  # unit tests
  serve-unit:
    build:
      context: ../../
      dockerfile: projects/entity-linking/serve/Dockerfile
      target: ${TARGET_BUILD_STAGE:-development}
      network: host
      args:
        AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID:-063759612765}
        PROJECT: entity-linking
        COMPONENT: serve
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG}
    image: ${AWS_ACCOUNT_ID:-063759612765}.dkr.ecr.us-east-1.amazonaws.com/entity-linking-serve:${IMAGE_TAG}
    command: [pytest, tests/unit, -ra, -vv, --capture=no]
    profiles: [unit]
    environment:
      ENVIRONMENT: ci
      DOCS_URL: /docs
      INTERNAL_ML_ENDPOINT_API_KEY: ${INTERNAL_ML_ENDPOINT_API_KEY}
    hostname: onclusiveml
    networks:
      - onclusive-net

  # integration tests
  serve-integration:
    build:
      context: ../../
      dockerfile: projects/entity-linking/serve/Dockerfile
      target: ${TARGET_BUILD_STAGE:-development}
      network: host
      args:
        AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID:-063759612765}
        PROJECT: entity-linking
        COMPONENT: serve
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG}
    image: ${AWS_ACCOUNT_ID:-063759612765}.dkr.ecr.us-east-1.amazonaws.com/entity-linking-serve:${IMAGE_TAG:-latest}
    command: [pytest, tests/integration, -ra, -vv, --capture=no]
    profiles: [integration]
    environment:
      ENVIRONMENT: ci
      DOCS_URL: /docs
    hostname: onclusiveml
    networks:
      - onclusive-net

networks:
  onclusive-net:
