[tool.poetry]
name = "sentiment-backfill"
version = "0.1.0"
description = ""
authors = ["Szymon Aptacy <szymon.aptacy@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
<<<<<<< HEAD
python = "3.9.19"
data = {path = "../../../libs/data"}
=======
python = "3.8.16"
beam = {path = "../../../libs/beam"}
>>>>>>> develop
core = {path = "../../../libs/core"}
serving = {path = "../../../libs/serving"}

[tool.poetry.group.dev.dependencies]
pytest = "7.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
