""" Constants """

# 3rd party libraries
from pydantic import BaseModel


class Item(BaseModel):
    """
    Class to represent special characters

    Args:
        char (str): character
        unicode_int (optional): unicode representation of character in integer format

    """

    char: str
    unicode_int: int


SPECIAL_CHARACTERS_AND_UNICODE = [
    Item(**{"char": "։", "unicode_int": 1417}),
    Item(**{"char": "؟", "unicode_int": 1567}),
    Item(**{"char": "۔", "unicode_int": 1748}),
    Item(**{"char": "܀", "unicode_int": 1792}),
    Item(**{"char": "܁", "unicode_int": 1793}),
    Item(**{"char": "܂", "unicode_int": 1794}),
    Item(**{"char": "߹", "unicode_int": 2041}),
    Item(**{"char": "।", "unicode_int": 2404}),
    Item(**{"char": "॥", "unicode_int": 2405}),
    Item(**{"char": "၊", "unicode_int": 4170}),
    Item(**{"char": "။", "unicode_int": 4171}),
    Item(**{"char": "።", "unicode_int": 4962}),
    Item(**{"char": "፧", "unicode_int": 4967}),
    Item(**{"char": "፨", "unicode_int": 4968}),
    Item(**{"char": "᙮", "unicode_int": 5742}),
    Item(**{"char": "᜵", "unicode_int": 5941}),
    Item(**{"char": "᜶", "unicode_int": 5942}),
    Item(**{"char": "᠃", "unicode_int": 6147}),
    Item(**{"char": "᠉", "unicode_int": 6153}),
    Item(**{"char": "᥄", "unicode_int": 6468}),
    Item(**{"char": "᥅", "unicode_int": 6469}),
    Item(**{"char": "᪨", "unicode_int": 6824}),
    Item(**{"char": "᪩", "unicode_int": 6825}),
    Item(**{"char": "᪪", "unicode_int": 6826}),
    Item(**{"char": "᪫", "unicode_int": 6827}),
    Item(**{"char": "᭚", "unicode_int": 7002}),
    Item(**{"char": "᭛", "unicode_int": 7003}),
    Item(**{"char": "᭞", "unicode_int": 7006}),
    Item(**{"char": "᭟", "unicode_int": 7007}),
    Item(**{"char": "᰻", "unicode_int": 7227}),
    Item(**{"char": "᰼", "unicode_int": 7228}),
    Item(**{"char": "᱾", "unicode_int": 7294}),
    Item(**{"char": "᱿", "unicode_int": 7295}),
    Item(**{"char": "‼", "unicode_int": 8252}),
    Item(**{"char": "‽", "unicode_int": 8253}),
    Item(**{"char": "⁇", "unicode_int": 8263}),
    Item(**{"char": "⁈", "unicode_int": 8264}),
    Item(**{"char": "⁉", "unicode_int": 8265}),
    Item(**{"char": "⸮", "unicode_int": 11822}),
    Item(**{"char": "⸼", "unicode_int": 11836}),
    Item(**{"char": "꓿", "unicode_int": 42239}),
    Item(**{"char": "꘎", "unicode_int": 42510}),
    Item(**{"char": "꘏", "unicode_int": 42511}),
    Item(**{"char": "꛳", "unicode_int": 42739}),
    Item(**{"char": "꛷", "unicode_int": 42743}),
    Item(**{"char": "꡶", "unicode_int": 43126}),
    Item(**{"char": "꡷", "unicode_int": 43127}),
    Item(**{"char": "꣎", "unicode_int": 43214}),
    Item(**{"char": "꣏", "unicode_int": 43215}),
    Item(**{"char": "꤯", "unicode_int": 43311}),
    Item(**{"char": "꧈", "unicode_int": 43464}),
    Item(**{"char": "꧉", "unicode_int": 43465}),
    Item(**{"char": "꩝", "unicode_int": 43613}),
    Item(**{"char": "꩞", "unicode_int": 43614}),
    Item(**{"char": "꩟", "unicode_int": 43615}),
    Item(**{"char": "꫰", "unicode_int": 43760}),
    Item(**{"char": "꫱", "unicode_int": 43761}),
    Item(**{"char": "꯫", "unicode_int": 44011}),
    Item(**{"char": "﹒", "unicode_int": 65106}),
    Item(**{"char": "﹖", "unicode_int": 65110}),
    Item(**{"char": "﹗", "unicode_int": 65111}),
    Item(**{"char": "！", "unicode_int": 65281}),
    Item(**{"char": "．", "unicode_int": 65294}),
    Item(**{"char": "？", "unicode_int": 65311}),
    Item(**{"char": "𐩖", "unicode_int": 68182}),
    Item(**{"char": "𐩗", "unicode_int": 68183}),
    Item(**{"char": "𑁇", "unicode_int": 69703}),
    Item(**{"char": "𑁈", "unicode_int": 69704}),
    Item(**{"char": "𑂾", "unicode_int": 69822}),
    Item(**{"char": "𑂿", "unicode_int": 69823}),
    Item(**{"char": "𑃀", "unicode_int": 69824}),
    Item(**{"char": "𑃁", "unicode_int": 69825}),
    Item(**{"char": "𑅁", "unicode_int": 69953}),
    Item(**{"char": "𑅂", "unicode_int": 69954}),
    Item(**{"char": "𑅃", "unicode_int": 69955}),
    Item(**{"char": "𑇅", "unicode_int": 70085}),
    Item(**{"char": "𑇆", "unicode_int": 70086}),
    Item(**{"char": "𑇍", "unicode_int": 70093}),
    Item(**{"char": "𑇞", "unicode_int": 70110}),
    Item(**{"char": "𑇟", "unicode_int": 70111}),
    Item(**{"char": "𑈸", "unicode_int": 70200}),
    Item(**{"char": "𑈹", "unicode_int": 70201}),
    Item(**{"char": "𑈻", "unicode_int": 70203}),
    Item(**{"char": "𑈼", "unicode_int": 70204}),
    Item(**{"char": "𑊩", "unicode_int": 70313}),
    Item(**{"char": "𑑋", "unicode_int": 70731}),
    Item(**{"char": "𑑌", "unicode_int": 70732}),
    Item(**{"char": "𑗂", "unicode_int": 71106}),
    Item(**{"char": "𑗃", "unicode_int": 71107}),
    Item(**{"char": "𑗉", "unicode_int": 71113}),
    Item(**{"char": "𑗊", "unicode_int": 71114}),
    Item(**{"char": "𑗋", "unicode_int": 71115}),
    Item(**{"char": "𑗌", "unicode_int": 71116}),
    Item(**{"char": "𑗍", "unicode_int": 71117}),
    Item(**{"char": "𑗎", "unicode_int": 71118}),
    Item(**{"char": "𑗏", "unicode_int": 71119}),
    Item(**{"char": "𑗐", "unicode_int": 71120}),
    Item(**{"char": "𑗑", "unicode_int": 71121}),
    Item(**{"char": "𑗒", "unicode_int": 71122}),
    Item(**{"char": "𑗓", "unicode_int": 71123}),
    Item(**{"char": "𑗔", "unicode_int": 71124}),
    Item(**{"char": "𑗕", "unicode_int": 71125}),
    Item(**{"char": "𑗖", "unicode_int": 71126}),
    Item(**{"char": "𑗗", "unicode_int": 71127}),
    Item(**{"char": "𑙁", "unicode_int": 71233}),
    Item(**{"char": "𑙂", "unicode_int": 71234}),
    Item(**{"char": "𑜼", "unicode_int": 71484}),
    Item(**{"char": "𑜽", "unicode_int": 71485}),
    Item(**{"char": "𑜾", "unicode_int": 71486}),
    Item(**{"char": "𑩂", "unicode_int": 72258}),
    Item(**{"char": "𑩃", "unicode_int": 72259}),
    Item(**{"char": "𑪛", "unicode_int": 72347}),
    Item(**{"char": "𑪜", "unicode_int": 72348}),
    Item(**{"char": "𑱁", "unicode_int": 72769}),
    Item(**{"char": "𑱂", "unicode_int": 72770}),
    Item(**{"char": "𖩮", "unicode_int": 92782}),
    Item(**{"char": "𖩯", "unicode_int": 92783}),
    Item(**{"char": "𖫵", "unicode_int": 92917}),
    Item(**{"char": "𖬷", "unicode_int": 92983}),
    Item(**{"char": "𖬸", "unicode_int": 92984}),
    Item(**{"char": "𖭄", "unicode_int": 92996}),
    Item(**{"char": "𛲟", "unicode_int": 113823}),
    Item(**{"char": "𝪈", "unicode_int": 121480}),
    Item(**{"char": "。", "unicode_int": 12290}),
]

SPECIAL_CHARACTERS = [item.char for item in SPECIAL_CHARACTERS_AND_UNICODE]
