[tool.poetry]
name = "keywords-serve"
version = "0.1.0"
description = "Implementation of Keywords Extraction API using neuron compiled models and internal libraries."
authors = ["Sebastian Scherer <sebastian.scherer@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.8.16"
core = {path = "../../../libs/core"}
models = {path = "../../../libs/models"}
serving = {path = "../../../libs/serving"}

[tool.poetry.group.dev.dependencies]
pytest = "7.2.0"
pytest-mock = "3.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "aws-neuron"
url = "https://pip.repos.neuron.amazonaws.com/"
default = false
secondary = true
