[tool.poetry]
name = "iptc-train"
version = "0.1.0"
description = "Docker image for registering model for named entity recognition"
authors = ["Jian <jian.tong@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.8.16"
torch = "1.12.1"
transformers = "4.31.0"
tracking = {path = "../../../libs/tracking"}
models = {path = "../../../libs/models"}
train = {path = "../../../libs/training"}

[tool.poetry.group.dev.dependencies]
pytest = "7.2.0"

[[tool.poetry.source]]
name = "aws-neuron"
url = "https://pip.repos.neuron.amazonaws.com/"
default = false
secondary = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
