[tool.poetry]
name = "iptc-train"
version = "0.1.0"
description = "Docker image for registering model for named entity recognition"
authors = ["Jian <jian.tong@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.8.16"
torch = "1.12.1"
transformers = "4.33.1"
tracking = {path = "../../../libs/tracking"}
data = {path = "../../../libs/data"}
train = {path = "../../../libs/training"}

[tool.poetry.group.dev.dependencies]
pytest = "7.2.0"

[[tool.poetry.source]]
name = "pipy-nvidia"
url = "https://pypi.nvidia.com"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
