[tool.poetry]
name = "transcript-segmentation-serve"
version = "0.1.0"
description = "Implementation Transcript Segmentation API"
authors = ["Syed Reza <syed.reza@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.9.19"
serving = {path = "../../../libs/serving"}
tracking = {path = "../../../libs/tracking"}
rapidfuzz = "3.7.0"

[tool.poetry.group.dev.dependencies]
pytest = "7.2.0"
pytest-order = "1.1.0"
pytest-mock = "3.10.0"
httpx = "0.25.0"

[tool.poetry.group.debug.dependencies]
debugpy = "1.8.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
