---
version : '3.9'

services:
  # =============================================
  # SERVE
  # =============================================

  # serving image
  serve:
    build:
      context: ../../
      dockerfile: projects/lsh/serve/Dockerfile
      target: ${TARGET_BUILD_STAGE:-development}
      network: host
      args:
        AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID:-063759612765}
        PROJECT: lsh
        COMPONENT: serve
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG}
    image: ${AWS_ACCOUNT_ID:-063759612765}.dkr.ecr.us-east-1.amazonaws.com/lsh-serve:${IMAGE_TAG:-latest}
    command: [uvicorn, src.app:app, --host, 0.0.0.0, --port, '8080', --reload, --log-level, debug]
    profiles: [serve]
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: serve
        target: /home/projects/lsh/serve
    environment:
      ENVIRONMENT: dev
      DOCS_URL: /lsh/docs
    hostname: onclusiveml
    networks:
      - onclusive-net
  # unit tests
  serve-unit:
    image: ${AWS_ACCOUNT_ID:-063759612765}.dkr.ecr.us-east-1.amazonaws.com/lsh-serve:${IMAGE_TAG:-latest}
    command: [pytest, tests/unit, -ra, -vv, --capture=no]
    profiles: [unit]
    volumes:
      - type: bind
        source: serve
        target: /home/projects/lsh/serve
    environment:
      ENVIRONMENT: dev
      DOCS_URL: /lsh/docs
    hostname: onclusiveml
    networks:
      - onclusive-net

  # integration tests
  serve-integration:
    image: ${AWS_ACCOUNT_ID:-063759612765}.dkr.ecr.us-east-1.amazonaws.com/lsh-serve:${IMAGE_TAG:-latest}
    command: [pytest, tests/integration, -ra, -vv, --capture=no]
    profiles: [integration]
    volumes:
      - type: bind
        source: serve
        target: /home/projects/lsh/serve
    environment:
      ENVIRONMENT: dev
      DOCS_URL: /lsh/docs
    hostname: onclusiveml
    networks:
      - onclusive-net


networks:
  onclusive-net:
