[tool.poetry]
name = "topic-backfill"
version = "0.1.0"
description = "BERTopic enrichment"
authors = ["Nutchapol Dendumrongsup <nutch.den@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.8.16"
data = {path = "../../../libs/data"}
core = {path = "../../../libs/core"}
serving = {path = "../../../libs/serving"}

[tool.poetry.group.dev.dependencies]
pytest = "7.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
