[tool.poetry]
name = "topic-backfill"
version = "0.1.0"
description = "Backfill topic"
authors = ["Yuzhou Gao <yuzhou.gao@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.8.16"
numpy = ">=1.21.0,<1.22.0"
pandas = "1.3.5"
packaging = "21.3"


[tool.poetry.group.dev.dependencies]
pytest = "7.2.0"
pytest-order = "1.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
combine_as_imports = false
