[tool.poetry]
name = "ner-compile"
version = "0.1.0"
description = "Implementation of NER model compilation, including validation."
authors = ["Syed Reza <syed.reza@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.8.16"
tracking = {path = "../../../libs/tracking"}
models = {path = "../../../libs/models"}

[tool.poetry.group.dev.dependencies]
pytest = "7.2.0"
pytest-mock = "3.10.0"


[[tool.poetry.source]]
name = "aws-neuron"
url = "https://pip.repos.neuron.amazonaws.com/"
default = false
secondary = true

[tool.poetry.group.debug.dependencies]
debugpy = "1.8.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
