[tool.poetry]
name = "lsh-serve"
version = "0.1.0"
description = "Implementation LSH API"
authors = ["Amaury de Guillebon <amaury.deguillebon@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.8.16"
regex = "2022.10.31"

core = {path = "../../../libs/core"}
hashing = {path = "../../../libs/hashing"}
serving = {path = "../../../libs/serving"}
tracking = {path = "../../../libs/tracking"}

[tool.poetry.group.dev.dependencies]
pytest = "7.2.0"
pytest-order = "1.1.0"
pytest-mock = "3.10.0"
httpx = "0.25.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
