[tool.poetry]
name = "prompt-manager-backend"
version = "0.1.0"
description = "Backend for Prompt Manager Tool"
authors = ["Rene Jean Corneille <rene-jean.corneille@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.9.19"
core = {path = "../../../libs/core"}
openai = "^1.3.4"
python-slugify = "8.0.1"
redis = "4.5.5"
python-redis-cache = "2.1.2"
PyGithub = "2.2.0"
dyntastic = "0.15.0"
llms = {path = "../../../libs/llms"}
typing-inspect = "0.8.0"
xxhash = "3.4.1"
boto3 = "1.35.12"
fastapi = "0.110.2"
uvicorn = "^0.30.6"
celery = "5.4.0"

[tool.poetry.group.dev.dependencies]
pytest = "7.2.0"
httpx = "0.23.3"
pytest-ordering = "^0.6"

[tool.poetry.group.debug.dependencies]
debugpy = "1.8.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
