[tool.poetry]
name = "Entity linking ingest"
version = "0.1.0"
description = "Ingesting and building vector store for entity linking data"
authors = ["Ivan Okhotnikov <ivan.okhotnikov@onclusive.com>"]

[tool.poetry.dependencies]
python = "3.9.19"
tracking = {path = "../../../libs/tracking"}
torch = "1.12.1"
redis = "^5.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "7.2.0"

[tool.poetry.group.debug.dependencies]
debugpy = "1.8.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
