[tool.poetry]
name = "gch-summarization-train"
version = "0.1.0"
description = "Docker image for registering model for named entity recognition"
authors = ["Zheyuan Hu <zheyuan.hu@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.8.16"
torch = "1.9.1"
transformers = "4.25.0"
core = {path = "../../../libs/core"}
tracking = {path = "../../../libs/tracking"}
sentencepiece = "^0.1.99"

[tool.poetry.group.dev.dependencies]
pytest = "7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
