[tool.poetry]
name = "entity-linking-backfill"
version = "0.1.0"
description = ""
authors = ["Rene-Jean Corneille <rene-jean.corneille@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.8.16"
data = {path = "../../../libs/data"}
core = {path = "../../../libs/core"}
serving = {path = "../../../libs/serving"}

[tool.poetry.group.dev.dependencies]
pytest = "7.2.2"
confluent_kafka = "2.3.0"

[tool.poetry.group.debug.dependencies]
debugpy = "1.8.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
