version: "3.9"

services:
  backend:
    build:
      context: ../../
      dockerfile: apps/entity-fishing/backend/Dockerfile
      target: ${TARGET_BUILD_STAGE:-development}
      network: host
      args:
        AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID:-063759612765}
        APP_NAME: entity-fishing
        APP_COMPONENT: backend
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG-v2023.3.2}
    image: ${AWS_ACCOUNT_ID:-063759612765}.dkr.ecr.us-east-1.amazonaws.com/entity-fishing-backend:${IMAGE_TAG:-latest}
    command:
      [
        "./gradlew",
        "--no-daemon",
        "run",
        "-x",
        "compileJava",
        "-x",
        "processResources",
        "-x",
        "classes",
      ]
    profiles: ["backend"]
    ports:
      - 4000:4000
    environment:
      ENVIRONMENT: dev
    networks:
      - onclusive-net

  backend-unit:
    build:
      context: ../../
      dockerfile: apps/entity-fishing/backend/Dockerfile
      target: ${TARGET_BUILD_STAGE:-development}
      network: host
      args:
        AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID:-063759612765}
        APP_NAME: entity-fishing
        APP_COMPONENT: backend
        BASE_IMAGE_TAG: v2023.3.2
    image: ${AWS_ACCOUNT_ID:-063759612765}.dkr.ecr.us-east-1.amazonaws.com/entity-fishing-backend:${IMAGE_TAG:-latest}
    command: ["./gradlew", "test"]
    profiles: ["unit"]
    environment:
      ENVIRONMENT: dev
    networks:
      - onclusive-net

networks:
  onclusive-net:
