"""Constants."""

SAMPLE_INFERENCE = {
    "en": "Sky News announces slate of special programming for the appointment of the UK's new Prime Minister. Sky News' political programming will expand ahead of a momentous week in UK politics with the impending announcement of the new Prime Minister. Sky News' key political programmes will return to bring audiences in-depth discussion and analysis of all the latest news with live coverage from Downing Street and Westminster. Head of Sky News, John Ryley: 'This is a momentous week in British politics, where a new Prime Minister will take on an in-tray bursting with crunch decisions.",  # noqa: E501
    "fr": "Sky News annonce une série de programmes spéciaux pour la nomination du nouveau Premier ministre du Royaume-Uni. La programmation politique de Sky News s'élargira avant une semaine mémorable dans la politique britannique avec l'annonce imminente du nouveau Premier ministre. Les principaux programmes politiques de Sky News reviendront pour offrir aux téléspectateurs des discussions approfondies et des analyses de toutes les dernières nouvelles avec une couverture en direct de Downing Street et de Westminster. Le directeur de Sky News, John Ryley : 'C'est une semaine mémorable dans la politique britannique, où un nouveau Premier ministre va prendre en charge une liste de décisions cruciales.",  # noqa: E501
    "de": "Sky News kündigt eine Reihe von Sonderprogrammen für die Ernennung des neuen Premierministers des Vereinigten Königreichs an. Das politische Programm von Sky News wird im Vorfeld einer bedeutsamen Woche in der britischen Politik mit der bevorstehenden Bekanntgabe des neuen Premierministers ausgeweitet. Die wichtigsten politischen Sendungen von Sky News werden zurückkehren, um dem Publikum eine ausführliche Diskussion und Analyse aller aktuellen Nachrichten mit Live-Berichterstattung aus der Downing Street und Westminster zu bieten. John Ryley, Leiter von Sky News: 'Dies ist eine bedeutsame Woche in der britischen Politik, in der ein neuer Premierminister eine Fülle von wichtigen Entscheidungen treffen wird",  # noqa: E501
    "es": "Sky News anuncia una serie de programas especiales para el nombramiento del nuevo Primer Ministro del Reino Unido. La programación política de Sky News se expandirá ante una semana trascendental en la política británica con el inminente anuncio del nuevo Primer Ministro. Los programas políticos clave de Sky News volverán para ofrecer a las audiencias una discusión y análisis en profundidad de todas las últimas noticias con cobertura en vivo desde Downing Street y Westminster. Jefe de Sky News, John Ryley: 'Esta es una semana trascendental en la política británica, donde un nuevo Primer Ministro se enfrentará a una bandeja de entrada llena de decisiones cruciales.",  # noqa: E501
    "ca": "Sky News anuncia una programació especial per a la designació del nou Primer Ministre del Regne Unit. La programació política de Sky News s'ampliarà en previsió d'una setmana molt important en la política britànica, amb l'anunci imminent del nou Primer Ministre. Els principals programes polítics de Sky News tornaran per portar als espectadors un debat i anàlisi en profunditat de totes les últimes notícies amb cobertura en directe des de Downing Street i Westminster. Cap de Sky News, John Ryley: 'Aquesta és una setmana crucial en la política britànica, on un nou Primer Ministre haurà de fer front a una safata plena de decisions molt importants'.",  # noqa: E501
    "it": "Sky News annuncia una serie di programmi speciali per la nomina del nuovo Primo Ministro del Regno Unito. La programmazione politica di Sky News si espanderà in vista di una settimana significativa nella politica britannica con l'imminente annuncio del nuovo Primo Ministro. I principali programmi politici di Sky News torneranno per offrire al pubblico discussioni approfondite e analisi di tutte le ultime notizie con copertura in diretta da Downing Street e Westminster. Direttore di Sky News, John Ryley: 'Questa è una settimana significativa nella politica britannica, dove un nuovo Primo Ministro si troverà di fronte a un vassoio traboccante di decisioni cruciali",  # noqa: E501
}
