[tool.poetry]
name = "ner-train"
version = "0.1.0"
description = "Docker image for registering model for named entity recognition"
authors = ["Syed Reza <syed.reza@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.8.16"
torch = "1.9.1"
transformers = "4.17.0"
sentencepiece = "0.1.99"
protobuf = "3.20.0"

core = {path = "../../../libs/core"}
tracking = {path = "../../../libs/tracking"}

[tool.poetry.group.dev.dependencies]
pytest = "7.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
