[tool.poetry]
name = "entity-linking-train"
version = "0.1.0"
description = "Docker image for registering model for entity linking"
authors = ["Nutch <nutch.den@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.9.19"
huggingface-hub = "0.22.2"
core = {path = "../../../libs/core"}
tracking = {path = "../../../libs/tracking"}

[tool.poetry.group.dev.dependencies]
pytest = "7.2.0"

[tool.poetry.group.debug.dependencies]
debugpy = "1.8.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
