version: "3.9"

services:
  serve:
    build:
      context: ../../
      dockerfile: projects/keywords/serve/Dockerfile
      args:
        PROJECT: keywords
        COMPONENT: serve
      target: development
    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: serve
        target: /home/projects/keywords/serve
    environment:
      DOCS_URL: /docs
    hostname: onclusive-ml
    networks: [onclusive-net]
  train:
    context: ../../
    dockerfile: projects/keywords/train/Dockerfile
    args:
      PROJECT: keywords
      COMPONENT: train
    target: development
    volumes:
      - type: bind
        source: train
        target: /home/projects/keywords/train
    environment:
      DOCS_URL: /docs
    hostname: onclusive-ml
    networks: [onclusive-net]

networks:
  onclusive-net:
