[tool.poetry]
name = "summarization-serve"
version = "0.1.0"
description = "Implementation of Summarization API using OpenAI's GPT3 models"
authors = ["Syed Reza <syed.reza@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.9.19"
openai = "0.27.2"
regex = "2022.10.31"

core = {path = "../../../libs/core"}
serving = {path = "../../../libs/serving"}
nlp = {path = "../../../libs/nlp"}

[tool.poetry.group.dev.dependencies]
pytest = "7.2.0"
pytest-mock = "3.10.0"
pytest-order = "1.1.0"

[tool.poetry.group.debug.dependencies]
debugpy = "1.8.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
