[tool.poetry]
name = "keywords-train"
version = "0.1.0"
description = "Docker image for registering a trained model for keywords extraction."
authors = ["Sebastian Scherer <sebastian.scherer@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.8.16"
keybert = "^0.7.0"
torch = "1.12.1"
transformers = "^4.27.4"
core = {path = "../../../libs/core"}
tracking = {path = "../../../libs/tracking"}

[tool.poetry.group.dev.dependencies]
pytest = "7.2.0"

[tool.poetry.group.debug.dependencies]
debugpy = "1.8.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
