[tool.poetry]
name = "topic-detection-serve"
version = "0.1.0"
description = "Implementation of topic detection API using OpenAI's GPT4 models"
authors = ["Yuzhou Gao <yuzhou.gao@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.8.16"
openai = "0.27.2"
regex = "2022.10.31"

core = {path = "../../../libs/core"}
types-requests = "^2.31.0.2"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
pytest = "7.2.0"
pytest-mock = "3.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
