[tool.poetry]
name = "topic-detection-serve"
version = "0.1.0"
description = "Implementation topic-detection API"
authors = ["Yuzhou Gao <yuzhou.gao@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.8.16"
regex = "2022.10.31"

core = {path = "../../../libs/core"}
serving = {path = "../../../libs/serving"}
types-requests = "^2.31.0.2"
requests = "^2.31.0"
httpx = "^0.24.1"

[tool.poetry.group.dev.dependencies]
pytest = "7.2.0"
pytest-order = "1.1.0"
pytest-mock = "3.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
