---
name: Apps
on  :
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: Environment where code is deployed [prod, dev]
      app:
        required: true
        type: string
        description: App name.
      component:
        required: true
        type: string
        description: Component to build, test and deploy [frontend, backend]
      tag:
        required: true
        type: string
        description: Version tag of image.
      integration:
        required: true
        default: true
        type: boolean
        description: Whether to run integrations.
      functional:
        required: false
        default: false
        type: boolean
        description: Whether to run functional test suite.
      release:
        required: true
        default: true
        type: boolean
        description: If false, only the app components that have been changed are ran, otherwise every app component is ran.
      use-cache:
        type: boolean
        required: false
        default: true
        description: Whether to use docker caching during building and pushing of the images.
    secrets:
      AWS_ACCOUNT_ID:
        required: true
        description: AWS account ID.
      AWS_DEFAULT_REGION:
        required: true
        description: AWS account region
      AWS_ACCESS_KEY_ID:
        required: true
        description: AWS access key ID.
      AWS_SECRET_ACCESS_KEY:
        required: true
        description: AWS secret access key
      PROMPT_REGISTRY_APP_ID:
        required: true
        description: Prompt registry app ID.
      PROMPT_REGISTRY_APP_PRIVATE_KEY:
        required: true
        description: Prompt registry app private key.
      OPENAI_API_KEY:
        required: true
        description: OPENAI Api key.

jobs:
  deploy:
    name: 'Build, test & deploy: ${{ inputs.app }}-${{ inputs.component }}'
    runs-on: ubuntu-20.04
    environment: ${{ inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: files-changed
        name: Get a list of modified files.
        with:
          list-files: shell
          filters: |
            this:
              - added | modified: 'apps/${{ inputs.app }}/${{ inputs.component }}/**'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        if: ${{ inputs.release || steps.files-changed.outputs.this == 'true' }}
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Free space
        run: |
          sudo rm -rfv \
            /usr/local/lib/android \
            /usr/share/dotnet \
            /opt/ghc \
            /usr/local/share/powershell \
            /usr/share/swift \
            /usr/local/.ghcup \
            /usr/lib/jvm \
            /var/lib/apt/lists/*

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get ECR credentials | ${{ inputs.environment }} ${{ inputs.app }}-${{ inputs.component }}
        if: ${{ inputs.release || steps.files-changed.outputs.this == 'true' }}
        run: make docker.login AWS_ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}"

      - name: Free space
        run: |
          sudo rm -rfv \
            /usr/local/lib/android \
            /usr/share/dotnet \
            /opt/ghc \
            /usr/local/share/powershell \
            /usr/share/swift \
            /usr/local/.ghcup \
            /usr/lib/jvm \
            /var/lib/apt/lists/*

      - name: Build App Docker Image | ${{ inputs.environment }}  ${{ inputs.app }}-${{ inputs.component }}
        if: ${{ inputs.release || steps.files-changed.outputs.this == 'true' }}
        run: |
          make apps.build/${{ inputs.app }} COMPONENT=${{ inputs.component }} \
          AWS_ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}" \
          PROMPT_REGISTRY_APP_ID="${{ secrets.PROMPT_REGISTRY_APP_ID }}" \
          PROMPT_REGISTRY_APP_PRIVATE_KEY="${{ secrets.PROMPT_REGISTRY_APP_PRIVATE_KEY }}" \
          DEPLOYMENT="${{ inputs.environment }}" \
          IMAGE_TAG="${{ inputs.tag }}" \
          TARGET_BUILD_STAGE="development" \
          PLATFORM="linux/amd64" \
          ENVIRONMENT="ci" \
          USE_DOCKER_CACHE="${{ inputs.use-cache }}"

      - name: Run app component unit tests | ${{ inputs.environment }} ${{ inputs.app }}-${{ inputs.component }}
        if: ${{ inputs.release || steps.files-changed.outputs.this == 'true' }}
        run: |
          make apps.unit/${{ inputs.app }} COMPONENT=${{ inputs.component }} \
          AWS_ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}" \
          PROMPT_REGISTRY_APP_ID="${{ secrets.PROMPT_REGISTRY_APP_ID }}" \
          PROMPT_REGISTRY_APP_PRIVATE_KEY="${{ secrets.PROMPT_REGISTRY_APP_PRIVATE_KEY }}" \
          IMAGE_TAG="${{ inputs.tag }}" \
          TARGET_BUILD_STAGE="development" \
          PLATFORM="linux/amd64" \
          DEPLOYMENT="${{ inputs.environment }}" \
          ENVIRONMENT="ci"

      - name: Run app component functional tests | ${{ inputs.environment }}  ${{ inputs.app }}-${{ inputs.component }}
        if: ${{ ( inputs.release || steps.files-changed.outputs.this == 'true' ) && inputs.functional }}
        run: |
          make apps.functional/${{ inputs.app }} COMPONENT=${{ inputs.component }} \
          AWS_ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}" \
          PROMPT_REGISTRY_APP_ID="${{ secrets.PROMPT_REGISTRY_APP_ID }}" \
          PROMPT_REGISTRY_APP_PRIVATE_KEY="${{ secrets.PROMPT_REGISTRY_APP_PRIVATE_KEY }}" \
          AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
          AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          IMAGE_TAG="${{ inputs.tag }}" \
          TARGET_BUILD_STAGE="development" \
          PLATFORM="linux/amd64" \
          ENVIRONMENT="ci"


      - name: Run app component integration tests | ${{ inputs.environment }}  ${{ inputs.app }}-${{ inputs.component }}
        if: ${{ ( inputs.release || steps.files-changed.outputs.this == 'true' ) && inputs.integration }}
        run: |
          make apps.integration/${{ inputs.app }} COMPONENT=${{ inputs.component }} \
          AWS_ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}" \
          PROMPT_REGISTRY_APP_ID="${{ secrets.PROMPT_REGISTRY_APP_ID }}" \
          PROMPT_REGISTRY_APP_PRIVATE_KEY="${{ secrets.PROMPT_REGISTRY_APP_PRIVATE_KEY }}" \
          AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
          AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          IMAGE_TAG="${{ inputs.tag }}" \
          TARGET_BUILD_STAGE="development" \
          PLATFORM="linux/amd64" \
          ENVIRONMENT="ci"

      - name: Build Docker Image | ${{ inputs.environment }}  ${{ inputs.app }}-${{ inputs.component }}
        if: ${{ inputs.release || steps.files-changed.outputs.this == 'true' }}
        run: |
          make apps.build/${{ inputs.app }} COMPONENT=${{ inputs.component }} \
          AWS_ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}" \
          PROMPT_REGISTRY_APP_ID="${{ secrets.PROMPT_REGISTRY_APP_ID }}" \
          PROMPT_REGISTRY_APP_PRIVATE_KEY="${{ secrets.PROMPT_REGISTRY_APP_PRIVATE_KEY }}" \
          DEPLOYMENT="${{ inputs.environment }}" \
          IMAGE_TAG="${{ inputs.tag }}" \
          TARGET_BUILD_STAGE="production" \
          PLATFORM="linux/amd64" \
          ENVIRONMENT="ci" \
          USE_DOCKER_CACHE="${{ inputs.use-cache }}"

      - name: Push Docker image with version | ${{ inputs.environment }}  ${{ inputs.app }}-${{ inputs.component }}
        if: ${{ inputs.release || steps.files-changed.outputs.this == 'true' }}
        run: |
          make apps.deploy/${{ inputs.app }} COMPONENT=${{ inputs.component }} \
          AWS_ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}" \
          IMAGE_TAG="${{ inputs.tag }}" \
          ENVIRONMENT="ci"
