name: Model Compilation
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Environment where code is deployed [prod, stage]"
      project:
        required: true
        type: string
        description: "Project."
      tag:
        required: true
        type: string
        description: "Version tag of image providing the compilation runtime context."
      pull-request:
        required: true
        default: true
        type: boolean
        description: "Indicates whether this workflow is running for a Pull Request."
      upload-compiled-model:
        required: false
        type: boolean
        default: true
        description: "Whether to upload the compiled model to the Neptune AI model registry"
      self-hosted-runner-type:
        required: false
        default: inf1.6xlarge
        type: string
        description: "Which EC2 instance type to provide as a self hosted runner."
    secrets:
      AWS_ACCOUNT_ID:
        required: true
        description: "AWS account ID."
      AWS_DEFAULT_REGION:
        required: true
        description: "AWS account region"
      AWS_ACCESS_KEY_ID:
        required: true
        description: "AWS access key ID."
      AWS_SECRET_ACCESS_KEY:
        required: true
        description: "AWS secret access key"
      AWS_ROLE_TO_ASSUME:
        required: true
        description: "AWS IAM role to assume."
      GH_PERSONAL_ACCESS_TOKEN:
        required: true
        description: "Github PAT to allow EC2 instance to connect to Github repository content."

jobs:
  provision-runner:
    name: Start self-hosted EC2 runner
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: DeployManifests

      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-04b40c32c6992d916 # <- one of the first successful custom builds # ami-0bef6cc322bfff646 <- official amazon linux 2 - doesnt even have docker
          ec2-instance-type: ${{ inputs.self-hosted-runner-type }}
          subnet-id: subnet-0b4bfc562953af299
          security-group-id: sg-00def06a1c2518854
          # iam-role-name: ${{ secrets.AWS_ROLE_TO_ASSUME }} # optional, requires additional permissions
          # TODO: add timestamp and environment name to the instance name
          aws-resource-tags: > # optional, requires additional permissions
            [
              {"Key": "Name", "Value": "ml-ec2-github-runner"},
              {"Key": "GitHubRepository", "Value": "${{ github.repository }}"},
              {"Key": "Environment", "Value": "dev"},
              {"Key": "Stack", "Value": "mesh"},
              {"Key": "Billing", "Value": "ML"}
            ]

  customize-runner:
    name: Custom installations on runner
    uses: ./.github/workflows/_customize_runner.yaml
    needs: provision-runner
    with:
      runner-id: ${{ needs.provision-runner.outputs.label }}
      environment: ${{ inputs.environment }}
      setup-docker-compose: true
      setup-neuron: true

  register-compiled-model:
    name: Compile and register a base or trained model
    needs: [provision-runner, customize-runner]
    runs-on: ${{ needs.provision-runner.outputs.label }}
    environment: ${{ inputs.environment }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # - uses: dorny/paths-filter@v2
      #   id: files-changed
      #   name: Get a list of modified files.
      #   with:
      #     list-files: shell
      #     filters: |
      #       this:
      #         - added | modified: 'keywords/compile/config/.prod'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        #if: ${{ steps.files-changed.outputs.this == 'true' || !inputs.pull-request }}
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: DeployManifests

      - name: Get ECR credentials | ${{ inputs.environment }} ${{ inputs.image }}
        #if: ${{ steps.files-changed.outputs.this == 'true' || !inputs.pull-request }}
        run: make docker.login AWS_ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}"

      - name: Check tool versions
        run: |
          docker version
          docker compose version

      - name: Download uncompiled model
        #if: ${{ steps.files-changed.outputs.this == 'true' || !inputs.pull-request }}
        run: |
          echo 'Downloading Uncompiled Model'
          make projects.compile/${{ inputs.project }} \
            ENVIRONMENT=ci \
            PIPELINE_COMPONENT=download-model \
            AWS_ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}" \
            IMAGE_TAG="${{ inputs.tag }}"

      - name: Compile Model
        #if: ${{ steps.files-changed.outputs.this == 'true' || !inputs.pull-request }}
        run: |
          echo 'Compiling Model'
          make projects.compile/${{ inputs.project }} \
            ENVIRONMENT=ci \
            PIPELINE_COMPONENT=compile-model \
            AWS_ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}" \
            IMAGE_TAG="${{ inputs.tag }}"

      - name: Validate Compiled Model
        #if: ${{ steps.files-changed.outputs.this == 'true' || !inputs.pull-request }}
        run: |
          echo 'Validating Compiled Model'
          make projects.compile/${{ inputs.project }} \
            ENVIRONMENT=ci \
            PIPELINE_COMPONENT=validate-model \
            AWS_ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}" \
            IMAGE_TAG="${{ inputs.tag }}"

      - name: Upload Compiled Model
        #if: ${{ steps.files-changed.outputs.this == 'true' && inputs.upload-compiled-model || !inputs.pull-request }}
        run: |
          echo 'Uploading Compiled Model'
          make projects.compile/${{ inputs.project }} \
            ENVIRONMENT=ci \
            PIPELINE_COMPONENT=upload-model \
            AWS_ACCOUNT_ID="${{ secrets.AWS_ACCOUNT_ID }}" \
            IMAGE_TAG="${{ inputs.tag }}"

  stop-runner:
    name: Stop self-hosted EC2 runner
    needs: [provision-runner, register-compiled-model]

    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
          role-session-name: DeployManifests
      - name: Stop EC2 runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: stop
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          label: ${{ needs.provision-runner.outputs.label }}
          ec2-instance-id: ${{ needs.provision-runner.outputs.ec2-instance-id }}
