name: Customize Runner
on:
  workflow_call:
    inputs:
      runner-id:
        required: true
        type: string
        description: "Unique runner label, serving as an identifier of the runner that we want to customize."
      environment:
        required: true
        type: string
        description: "Environment where code is deployed [prod, stage]"
      setup-docker-compose:
        required: true
        default: true
        type: boolean
        description: "Whether to set up docker compose on the runner."
      setup-neuron:
        required: true
        default: true
        type: boolean
        description: "Whether to set up neuron driver and runtime OS libraries on the runner."

jobs:
  set-up-runner:
    name: Customize self-hosted EC2 runner
    runs-on: ${{ inputs.runner-id }}
    env:
      ebs-mount-point: /mnt/ebs

    steps:
      - name: Check disks
        run: |
          df -h
          lsblk

      - name: Mount EBS volume
        run: |
          sudo file -s /dev/nvme1n1 # Check for EBS drive
          sudo fdisk -l # List all drives & partitions
          sudo mkfs -t xfs /dev/nvme1n1 # Create filesystem
          sudo mkdir /mnt/ebs # Create mount point
          sudo mount -t xfs -o nouuid /dev/nvme1n1 ${{ env.ebs-mount-point }} # Mount drive

      - name: Install neuron libraries
        if: ${{ inputs.setup-neuron }}
        run: |
          echo "Installing neuron libraries"
          sudo tee /etc/yum.repos.d/neuron.repo > /dev/null <<EOF
          [neuron]
          name=Neuron YUM Repository
          baseurl=https://yum.repos.neuron.amazonaws.com
          enabled=1
          metadata_expire=0
          EOF
          sudo rpm --import https://yum.repos.neuron.amazonaws.com/GPG-PUB-KEY-AMAZON-AWS-NEURON.PUB
          sudo yum update -y
          sudo yum install kernel-devel-$(uname -r) kernel-headers-$(uname -r) -y
          sudo yum install aws-neuronx-dkms-2.* -y
          sudo yum install aws-neuronx-tools-2.* -y
          export PATH=/opt/aws/neuron/bin:$PATH
          echo "Available neuron devicces:"
          neuron-ls

      - name: Install docker compose
        if: ${{ inputs.setup-docker-compose }}
        run: |
          echo "Stopping all docker processes"
          sudo systemctl stop docker
          sudo systemctl stop docker.socket
          sudo systemctl stop containerd
          echo "Installing docker compose"
          sudo yum update -y
          sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          sudo sed -i 's/$releasever/7/g' /etc/yum.repos.d/docker-ce.repo
          sudo yum install -y docker-compose-plugin jq
          echo "Configuring docker dir to mounted EBS volume"
          sudo touch /etc/docker/daemon.json
          sudo jq -n --arg docker_dir "${{ env.ebs-mount-point }}/docker" '{"data-root": $docker_dir}' > /etc/docker/daemon.json
          cat /etc/docker/daemon.json
          echo "Restarting docker"
          sudo systemctl enable docker
          sudo systemctl start docker
          echo "Docker installation file directory:"
          docker info -f '{{ .DockerRootDir}}'
          echo "Docker compose installation complete. Version:"
          docker compose version
