---
name: Internal Library
on  :
  workflow_call:
    inputs:
      lib:
        required: true
        type: string
        description: Library name.
      integration:
        required: true
        default: true
        type: boolean
        description: Whether to run integrations.
      functional:
        required: true
        default: true
        type: boolean
        description: Whether to run functional tests.
      python-version:
        required: false
        type: string
        description: Python version.
      poetry-version:
        required: false
        type: string
        description: Python version.
      release:
        required: true
        default: true
        type: boolean
        description: If false, only the libs that have been changed are ran, otherwise every lib is ran.
      apply-max-attempts:
        type: number
        default: 2
        description: Number of attempts to deploy manifests to cluster.
      apply-retry-wait-seconds:
        type: number
        default: 30
        description: Time (in  seconds) between attempts.

jobs:
  deploy:
    name: 'Install & test library: ${{ inputs. lib }}'
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: files-changed
        name: Get a list of modified files.
        with:
          list-files: shell
          filters: |
            this:
              - added | modified: 'libs/**'

      - name: Setup Python
        if: ${{ inputs.release || steps.files-changed.outputs.this == 'true' }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Setup Poetry
        if: ${{ inputs.release || steps.files-changed.outputs.this == 'true' }}
        uses: snok/install-poetry@v1
        with:
          version: ${{ inputs.poetry-version }}
          virtualenvs-create: false

      - name: Install lib dependencies
        if: ${{ inputs.release || steps.files-changed.outputs.this == 'true' }}
        uses: nick-fields/retry@v2
        with:
          max_attempts: ${{ inputs.apply-max-attempts }}
          retry_wait_seconds: ${{ inputs.apply-retry-wait-seconds }}
          timeout_minutes: 10
          command: make libs.install/${{ inputs.lib }}

      - name: Run unit tests
        if: ${{ inputs.release || steps.files-changed.outputs.this == 'true' }}
        run: make libs.unit/${{ inputs.lib }}

      - name: Run integration tests
        if: ${{ ( inputs.integration && inputs.release || steps.files-changed.outputs.this == 'true' ) && inputs.integration }}
        run: make libs.integration/${{ inputs.lib }}

      - name: Run functional tests
        if: ${{ ( inputs.functional && inputs.release || steps.files-changed.outputs.this == 'true' ) && inputs.functional }}
        run: make libs.functional/${{ inputs.lib }}
