---
name: Libs
on  :
  workflow_call:
    inputs:
      lib:
        required: true
        type: string
        description: Library name.
      integration:
        required: true
        default: true
        type: boolean
        description: Whether to run integrations.
      functional:
        required: true
        default: true
        type: boolean
        description: Whether to run functional tests.
      python-version:
        required: false
        type: string
        description: Python version.
      poetry-version:
        required: false
        type: string
        description: Python version.
      release:
        required: true
        default: true
        type: boolean
        description: If false, only the libs that have been changed are ran, otherwise every lib is ran.

jobs:
  deploy:
    name: 'Internal library: ${{ inputs. lib }}'
    runs-on: ubuntu-20.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: files-changed
        name: Get a list of modified files.
        with:
          list-files: shell
          filters: |
            this:
              - added | modified: 'libs/**'

      - name: Setup Python
        if: ${{ inputs.release || steps.files-changed.outputs.this == 'true' }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Setup Poetry
        if: ${{ inputs.release || steps.files-changed.outputs.this == 'true' }}
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ inputs.poetry-version }}

      - name: Install lib dependencies
        if: ${{ inputs.release || steps.files-changed.outputs.this == 'true' }}
        run: make libs.install/${{ inputs.lib }}

      - name: Run unit tests
        if: ${{ inputs.release || steps.files-changed.outputs.this == 'true' }}
        run: make libs.unit/${{ inputs.lib }}

      - name: Run integration tests
        if: ${{ ( inputs.integration && inputs.release || steps.files-changed.outputs.this == 'true' ) && inputs.integration }}
        run: make libs.integration/${{ inputs.lib }}

      - name: Run functional tests
        if: ${{ ( inputs.functional && inputs.release || steps.files-changed.outputs.this == 'true' ) && inputs.functional }}
        run: make libs.functional/${{ inputs.lib }}
