---
name: Retrieve repository state
on  :
  workflow_call:
    inputs:
      environment:
        required: true
        default: prod
        type: string
        description: Environment runtime for the development.
      pull-request:
        required: true
        default: true
        type: boolean
        description: Indicates whether this workflow is running for a Pull Request.
      base-ref:
        required: false
        type: string
        default: develop
        description: Source branch.
      head-ref:
        required: false
        type: string
        default: develop
        description: Release target branch.
      pre-release:
        required: false
        type: boolean
        default: false
        description: If true a pre-release is created.
      publish:
        required: false
        type: boolean
        default: true
        description: If true a pre-release is created.
      include-pre-releases:
        required: false
        type: boolean
        default: false
        description: Include pre releases as "full" releases when drafting release notes.
    secrets:
      GITHUB_TOKEN_:
        required: true
        description: Github Token to interact with repo.
    outputs:
      tag:
        description: Final tag to attach to images built within the workflow
        value: ${{ jobs.get-stage.outputs.tag }}
      version:
        description: Final tag to attach to images built within the workflow without the v prefix
        value: ${{ jobs.get-stage.outputs.version }}

jobs:

  check-github-state:
    name: Check github refs
    runs-on: ubuntu-latest

    steps:

      - name: Show all relevant github action context vars
        run: |
          echo github.actor: ${{ github.actor }}
          echo github.actor_id: ${{ github.actor_id }}
          echo github.ref_name: ${{ github.ref_name }}
          echo github.event_name: ${{ github.event_name }}
          echo "github.base_ref (PR only):" ${{ github.base_ref }}
          echo "github.head_ref (PR only):" ${{ github.head_ref }}
          echo github.ref: ${{ github.ref }}
          echo github.type: ${{ github.type }}
          echo github.run_id: ${{ github.run_id }}
          echo github.run_attempt: ${{ github.run_attempt }}

  get-stage:

    runs-on: ubuntu-20.04
    permissions:
      contents: write
      pull-requests: write
    environment: ${{ inputs.environment }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_ }}
    outputs:
      tag: ${{ steps.export-tag.outputs.tag }}
      version: ${{ steps.version-increment.outputs.version }}
      release-notes: ${{ steps.changelog.outputs.changelog }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Export current working directory
        id: export-working-dir
        run: |
          echo "workdir=$GITHUB_WORKSPACE" >> $GITHUB_OUTPUT

      - name: Tag Pull Request
        uses: srvaroa/labeler@v1.10.0
        if: ${{ inputs.pull-request }}
        with:
          config_path: .github/labeler.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_ }}

      - name: Lookup current version
        id: version-lookup
        run: ${{ steps.export-working-dir.outputs.workdir }}/bin/actions/version-lookup
        shell: bash

      - name: Get next version
        id: version-increment
        if: ${{ !inputs.pull-request }}
        run: ${{ steps.export-working-dir.outputs.workdir }}/bin/actions/version-increment
        shell: bash
        env:
          current_version: ${{ steps.version-lookup.outputs.CURRENT_VERSION }}
          is_pre_release: ${{ inputs.pre-release }}

      - name: Get short commit SHA
        id: get-commit-sha
        if: ${{ inputs.pull-request }}
        run: |
          sha=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})
          echo "tag=ci-$sha" >> $GITHUB_OUTPUT

      - name: Export tag
        id: export-tag
        run: |
          if [[ ${{ inputs.pull-request }} = true ]]; then
              echo "tag=ci-${{ github.run_id }}-${{ github.run_attempt }}" >> $GITHUB_OUTPUT
          else
              echo "tag=v${{ steps.version-increment.outputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Changelog
        id: changelog
        if: ${{ inputs.pull-request && inputs.base-ref == 'main' }}
        uses: mikepenz/release-changelog-builder-action@v4.1.0
        with:
          configuration: .github/changelog.json
          ignorePreReleases: false
          fromTag: ${{ steps.version-lookup.outputs.CURRENT_V_VERSION }}
          toTag: ${{ steps.version-increment.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update PR body
        id: update-pr-body
        if: ${{ inputs.pull-request && inputs.base-ref == 'main' }}
        uses: Perdoo/pull-request-update-body-action@v1.0.1
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.changelog.outputs.changelog }}
          override: true

      - name: Generate Release Notes
        uses: release-drafter/release-drafter@v5.25.0
        id: release-drafter
        if: ${{ !inputs.pull-request }}
        with:
          config-name: release-drafter.yaml
          publish: ${{ inputs.publish }}
          commitish: ${{ inputs.head-ref }}
          prerelease: ${{ inputs.pre-release }}
          tag: v${{ steps.version-increment.outputs.version }}
          name: v${{ steps.version-increment.outputs.version }}
          version: v${{ steps.version-increment.outputs.version }}
