name: Test container context capabilitiy
on:
  workflow_dispatch:
  push:
    branches:
      - prod
      - DS-375
  pull_request:
    branches:
      - prod
      - DS-375
    types:
      - opened
      - reopened
    inputs:
      image-name:
        required: false
        type: string
        default: python
        description: "The name of the container image providing the github action job context"
      image-version:
        required: false
        type: string
        default: 3.8.16
        description: "The version of the container image providing the github action job context"
jobs:
  get-image-reference:
    runs-on: ubuntu-latest
    outputs:
      image-reference: ${{ steps.set-image-reference.outputs.image-reference}}
    steps:
      - name: Check inputs
        run: |
          echo "Image name input: ${{ inputs.image-name }}"
          echo "Image version input: ${{ inputs.image-version }}"

      - name: Export versioned image reference
        id: set-image-reference
        run: echo "image-reference=${{ inputs.image-name }}:${{ inputs.image-version }}" >> "$GITHUB_OUTPUT"

      - name: Check versioned image reference
        run: echo "Using image ${{ steps.set-image-reference.outputs.image-reference }}"
  container-test-job:
    runs-on: ubuntu-latest
    needs: get-image-reference
    container:
      #image: ${{ inputs.image_name}}:${{ inputs.image_version }}
      #image: python:3.10-bullseye
      image: ${{ needs.set-image-reference.outputs.image-reference}}
      env:
        some_param: 'PARAMETER A'
      volumes:
        - my_docker_volume:/volume_mount # mounted volume sharing outputs between steps goes here
      options: --cpus 1 # --device /dev/neuron0 would go here
    steps:
      - name: Print out parameter
        run: echo $some_param