name: Test container context capabilitiy
on:
  workflow_dispatch:
  push:
    branches:
      - prod
      - DS-375
  pull_request:
    branches:
      - prod
      - DS-375
    types:
      - opened
      - reopened
    inputs:
      image_name:
        required: false
        type: string
        default: python
        description: "The name of the container image providing the github action job context"
      image_version:
        required: false
        type: string
        default: 3.8.16
        description: "The version of the container image providing the github action job context"
jobs:
  image-specifier:
    runs-on: ubuntu-latest
    outputs:
      image-version: ${{ steps.set-image-version.outputs.image-version}}
    steps:
      - name: Export versioned image reference
        id: set-image-version
        run: echo "image-version=${{ inputs.image_name }}:${{ inputs.image_name }}" >> "$GITHUB_OUTPUT"

      - name: Check versioned image reference
        run: echo Using image: ${{ steps.set-image-version.outputs.image-version}}
  container-test-job:
    runs-on: ubuntu-latest
    needs: image-specifier
    container:
      #image: ${{ inputs.image_name}}:${{ inputs.image_version }}
      #image: python:3.10-bullseye
      image: ${{ jobs.image-specifier.outputs.image-version}}
      env:
        some_param: 'PARAMETER A'
      volumes:
        - my_docker_volume:/volume_mount # mounted volume sharing outputs between steps goes here
      options: --cpus 1 # --device /dev/neuron0 would go here
    steps:
      - name: Print out parameter
        run: echo $some_param