version: "3.9"

services:
  # =============================================
  # SERVE
  # =============================================
  serve:
    build:
      context: ../../
      dockerfile: projects/summarization/serve/Dockerfile
      target: ${TARGET_BUILD_STAGE:-development}
      args:
        AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID:-063759612765}
        PROJECT: summarization
        COMPONENT: serve
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG:-v2023.3.2}
    image: ${AWS_ACCOUNT_ID:-063759612765}.dkr.ecr.us-east-1.amazonaws.com/summarization-serve:${IMAGE_TAG:-latest}
    command:
      [
        "uvicorn",
        "src.app:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
        "--log-level",
        "debug",
      ]
    profiles: ["serve"]
    ports:
      - 8000:8000
    environment:
      ENVIRONMENT: ci
      DOCS_URL: /docs
    hostname: onclusiveml
    networks:
      - onclusive-net

  serve-unit:
    build:
      context: ../../
      dockerfile: projects/summarization/serve/Dockerfile
      target: ${TARGET_BUILD_STAGE:-development}
      args:
        AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID:-063759612765}
        PROJECT: summarization
        COMPONENT: serve
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG:-v2023.3.2}
    image: ${AWS_ACCOUNT_ID:-063759612765}.dkr.ecr.us-east-1.amazonaws.com/summarization-serve:${IMAGE_TAG:-latest}
    command: ["pytest", "tests/unit", "-ra", "-vv", "--capture=no"]
    profiles: ["serve", "unit"]
    ports:
      - 8000:8000
    environment:
      ENVIRONMENT: ci
      DOCS_URL: /docs
    hostname: onclusiveml
    networks:
      - onclusive-net

  serve-integration:
    build:
      context: ../../
      dockerfile: projects/summarization/serve/Dockerfile
      target: ${TARGET_BUILD_STAGE:-development}
      args:
        AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID:-063759612765}
        PROJECT: summarization
        COMPONENT: serve
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG:-v2023.3.2}
    image: ${AWS_ACCOUNT_ID:-063759612765}.dkr.ecr.us-east-1.amazonaws.com/summarization-serve:${IMAGE_TAG:-latest}
    command: ["pytest", "tests/integration", "-ra", "-vv", "--capture=no"]
    profiles: ["serve", "integration"]
    ports:
      - 8000:8000
    environment:
      ENVIRONMENT: ci
      DOCS_URL: /docs
    hostname: onclusiveml
    networks:
      - onclusive-net

networks:
  onclusive-net:
