version: "3.9"

services:
  serve:
    profiles: ["serve"]
    image: onclusiveml/summarization-serve:latest
    ports:
      - "9000:9000"
    command: ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "9000"]
    environment:
      ENVIRONMENT: "dev"
    hostname: onclusive-ml
    networks: [onclusive-net]

networks:
  onclusive-net:
