---

services:
  # =============================================
  # SERVE
  # =============================================

  # serving image
  serve:
    volumes:
      - type: bind
        source: serve/src
        target: /projects/summarization/serve/src
      - type: bind
        source: serve/tests
        target: /projects/summarization/serve/tests
    build:
      context: ../../
      dockerfile: projects/summarization/serve/Dockerfile
      target: ${TARGET_BUILD_STAGE:-development}
      network: host
      args:
        AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID:-690763002009}
        PROJECT: summarization
        COMPONENT: serve
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG}
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-1.amazonaws.com/summarization-serve:${IMAGE_TAG:-latest}
    command: [python, -m, src.serve.__main__]
    profiles: [serve]
    ports:
      - 8888:8888
    environment:
      ONCLUSIVEML_SERVING_INTERNAL_ML_ENDPOINT_API_KEY: ${INTERNAL_ML_ENDPOINT_API_KEY:-1234}
      ONCLUSIVEML_SERVING_BETTERSTACK_ENABLE: true
      ONCLUSIVEML_SERVING_BETTERSTACK_API_TOKEN: ${ONCLUSIVEML_SERVING_BETTERSTACK_API_TOKEN}
      ONCLUSIVEML_SERVING_TRANSLATION_API: http://translation-serve:8001
    env_file: serve/config/dev.env
    depends_on:
      prompt-backend:
        condition: service_healthy
      translation-serve:
        condition: service_healthy
    hostname: onclusiveml
    networks:
      - onclusive-net

  serve-debug:
    build:
      context: ../../
      dockerfile: projects/summarization/serve/Dockerfile
      target: ${TARGET_BUILD_STAGE:-debugger}
      network: host
      args:
        AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID:-690763002009}
        PROJECT: summarization
        COMPONENT: serve
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG}
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-1.amazonaws.com/summarization-serve:${IMAGE_TAG:-latest}
    profiles: [debug]
    command: [python, -m, debugpy, --listen, 0.0.0.0:5678, --wait-for-client, -m, src.serve.__main__]
    ports:
      - 5678:5678
      - 8888:8888
    volumes:
      - type: bind
        source: serve/src
        target: /projects/summarization/serve/src
      - type: bind
        source: serve/tests
        target: /projects/summarization/serve/tests
    environment:
      ONCLUSIVEML_SERVING_INTERNAL_ML_ENDPOINT_API_KEY: ${INTERNAL_ML_ENDPOINT_API_KEY:-1234}
    env_file: serve/config/dev.env
    depends_on:
      prompt-backend:
        condition: service_healthy
    hostname: onclusiveml
    networks:
      - onclusive-net

  # unit tests
  serve-unit:
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-1.amazonaws.com/summarization-serve:${IMAGE_TAG:-latest}
    command: [python, -m, pytest, tests/unit, -ra, -vv, --capture=no]
    profiles: [unit]
    volumes:
      - type: bind
        source: serve/src
        target: /projects/summarization/serve/src
      - type: bind
        source: serve/tests
        target: /projects/summarization/serve/tests
    environment:
      ONCLUSIVEML_SERVING_INTERNAL_ML_ENDPOINT_API_KEY: ${INTERNAL_ML_ENDPOINT_API_KEY:-1234}
    env_file: serve/config/dev.env
    hostname: onclusiveml
    networks:
      - onclusive-net

  # integration tests
  serve-integration:
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-1.amazonaws.com/summarization-serve:${IMAGE_TAG:-latest}
    command: [python, -m, pytest, tests/integration, -ra, -vv, --capture=no]
    profiles: [integration]
    volumes:
      - type: bind
        source: serve/src
        target: /projects/summarization/serve/src
      - type: bind
        source: serve/tests
        target: /projects/summarization/serve/tests
    environment:
      ONCLUSIVEML_SERVING_INTERNAL_ML_ENDPOINT_API_KEY: ${INTERNAL_ML_ENDPOINT_API_KEY:-1234}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      REGION_NAME: ${REGION_NAME}
      BASE_IMAGE_TAG: ${BASE_IMAGE_TAG}
    env_file: serve/config/dev.env
    depends_on:
      prompt-backend:
        condition: service_healthy
      translation-serve:
        condition: service_healthy
    hostname: onclusiveml
    networks:
      - onclusive-net

  translation-serve:
    build:
      context: ../../
      dockerfile: projects/translation/serve/Dockerfile
      target: ${TARGET_BUILD_STAGE:-development}
      network: host
      args:
        AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID:-690763002009}
        PROJECT: translation
        COMPONENT: serve
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG}
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-1.amazonaws.com/translation-serve:${IMAGE_TAG:-latest}
    command: [python, -m, src.serve.__main__]
    profiles: [serve, integration, debug]
    ports:
      - 8001:8001
    volumes:
      - type: bind
        source: ~/.aws/
        target: /projects/translation/serve/.aws/
    env_file: ../../projects/translation/serve/config/dev.env
    healthcheck:
      test: [CMD, curl, -f, http://translation-serve:8001/translation/v1/ready]
      interval: 5s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - onclusive-net

  prompt-backend:
    build:
      context: ../../
      dockerfile: apps/prompt/backend/Dockerfile
      target: ${TARGET_BUILD_STAGE:-development}
      network: host
      args:
        AWS_ACCOUNT_ID: ${AWS_ACCOUNT_ID:-690763002009}
        APP_NAME: prompt
        APP_COMPONENT: backend
        BASE_IMAGE_TAG: ${BASE_IMAGE_TAG}
    image: ${AWS_ACCOUNT_ID:-690763002009}.dkr.ecr.us-east-1.amazonaws.com/prompt-backend:${IMAGE_TAG}
    command: [python, -m, uvicorn, src.app:app, --host, 0.0.0.0, --port, '4000', --reload, --log-level, debug]
    profiles: [serve, integration, debug]
    ports:
      - 4000:4000
    environment:
      ENVIRONMENT: dev
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-anything}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-anything}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-none}
      PROMPT_REGISTRY_APP_ID: ${PROMPT_REGISTRY_APP_ID}
      PROMPT_REGISTRY_APP_PRIVATE_KEY: ${PROMPT_REGISTRY_APP_PRIVATE_KEY}
      DOCS_URL: /docs
      REDIS_CONNECTION_STRING: redis://redisdb:6379
      DYNAMODB_HOST: http://dynamodb:8000
      BETTERSTACK_KEY: ${BETTERSTACK_KEY:-none}
    depends_on:
      dynamodb:
        condition: service_healthy
      redisdb:
        condition: service_healthy
    healthcheck:
      # NOTE: This hack is required so that the integration tests only start when the
      # databse is ready to receive requests.
      test: [CMD-SHELL, sleep 30s || exit 1]
      interval: 60s
      timeout: 40s
      retries: 5
      start_period: 90s
    networks:
      - onclusive-net

  dynamodb:
    command: -jar DynamoDBLocal.jar -sharedDb
    image: amazon/dynamodb-local:latest
    restart: always
    expose:
      - 8000
    ports:
      - 8000:8000
    profiles: [serve, integration, debug]
    healthcheck:
      # NOTE: This hack is required so that the integration tests only start when the
      # databse is ready to receive requests.
      test: [CMD-SHELL, sleep 3s || exit 1]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 10s
    networks:
      - onclusive-net

  redisdb:
    image: redis:7.0
    restart: always
    expose:
      - 6379
    ports:
      - 6379:6379
    profiles: [serve, integration, debug]
    healthcheck:
      # NOTE: This hack is required so that the integration tests only start when the
      # databse is ready to receive requests.
      test: [CMD-SHELL, sleep 3s || exit 1]
      interval: 5s
      retries: 5
      start_period: 5s
      timeout: 10s
    networks:
      - onclusive-net

networks:
  onclusive-net:
