[tool.poetry]
name = "ner-train"
version = "0.1.0"
description = "Docker image for registering model for named entity recognition"
authors = ["Syed Reza <syed.reza@onclusive.com>"]
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "3.9.19"
torch = "1.12.1"
transformers = "4.33.1"
numpy = "<2.0"
core = {path = "../../../libs/core"}
tracking = {path = "../../../libs/tracking"}

[tool.poetry.group.dev.dependencies]
pytest = "7.2.0"

[tool.poetry.group.debug.dependencies]
debugpy = "1.8.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
